### ISSUE TITLE
remove command fails with AttributeError: 'SolidFill' object has no attribute 'get_focus'

### ISSUE THREAD

**Issue by jenda1** [pazz/alot#1036]
each time I tried to run 'remove' command in thread view, I get the exception:

```
Traceback (most recent call last):
  File "/home/user/venv/bin/alot", line 11, in <module>
    load_entry_point('alot==0.6.0.dev0', 'console_scripts', 'alot')()
  File "/home/user/venv/local/lib/python2.7/site-packages/alot/__main__.py", line 128, in main
    UI(dbman, cmdstring)
  File "/home/user/venv/local/lib/python2.7/site-packages/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
    callback()
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/user/venv/local/lib/python2.7/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/user/venv/local/lib/python2.7/site-packages/alot/buffers.py", line 381, in render
    msg = self.get_selected_message()
  File "/home/user/venv/local/lib/python2.7/site-packages/alot/buffers.py", line 424, in get_selected_message
    return self.get_selected_messagetree()._message
  File "/home/user/venv/local/lib/python2.7/site-packages/alot/buffers.py", line 420, in get_selected_messagetree
    return self._nested_tree[self.body.get_focus()[1][:1]]
AttributeError: 'SolidFill' object has no attribute 'get_focus'
```

build from 333fcaed50296402aaf24f226d38ff93599bcd25 (Tue Feb 14 2017).

**Comment by pazz** [comment]
Thanks, I can conform this bug, it happens when you remove the last mail in a thread
and the UI tries to get the focussed message, which returns none as there are none.
