### ISSUE TITLE
UnicodeEncodeError when encrypting/signing mail with attachment whose filename contains UTF-8 character

### ISSUE THREAD

**Issue by aepsil0n** [pazz/alot#1047]
So I made a mundane text file called `bläh` (note the umlaut). Then I started alot, composed an message to myself (which is encrypted and signed by default) and attached `bläh` to it. This fails with the following stack trace:

```
INFO:globals:open command shell
INFO:envelope:attaching: [u'/home/eduard/bl\xe4h']
INFO:globals:open command shell
ERROR:ui:Traceback (most recent call last):
  File "/nix/store/im9nc5i333gsr4v9izgi72i88pbg4iny-python2.7-Twisted-16.4.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/nix/store/anh3m5770ailih53ssq170gzp925lxxy-python2.7-alot-0.5/lib/python2.7/site-packages/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/nix/store/im9nc5i333gsr4v9izgi72i88pbg4iny-python2.7-Twisted-16.4.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/nix/store/im9nc5i333gsr4v9izgi72i88pbg4iny-python2.7-Twisted-16.4.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/nix/store/im9nc5i333gsr4v9izgi72i88pbg4iny-python2.7-Twisted-16.4.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/nix/store/anh3m5770ailih53ssq170gzp925lxxy-python2.7-alot-0.5/lib/python2.7/site-packages/alot/commands/envelope.py", line 207, in apply
    self.mail = self.envelope.construct_mail()
  File "/nix/store/anh3m5770ailih53ssq170gzp925lxxy-python2.7-alot-0.5/lib/python2.7/site-packages/alot/db/envelope.py", line 234, in construct_mail
    plaintext = helper.email_as_string(unencrypted_msg)
  File "/nix/store/anh3m5770ailih53ssq170gzp925lxxy-python2.7-alot-0.5/lib/python2.7/site-packages/alot/helper.py", line 618, in email_as_string
    g.flatten(mail)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 249, in _handle_multipart_signed
    self._handle_multipart(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 108, in _write
    self._dispatch(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 134, in _dispatch
    meth(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 203, in _handle_multipart
    g.flatten(part, unixfrom=False)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/nix/store/3n3r10921c0mzfrq64hc4m2jzjk13qpr-python-2.7.13/lib/python2.7/email/generator.py", line 145, in _write_headers
    print >> self._fp, v
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 24: ordinal not in range(128)
```

I'm trying to see whether I can find the bug myself (never worked with the code base though).

**Comment by aepsil0n** [comment]
might be related to #879 perhaps?

**Comment by aepsil0n** [comment]
ah, another important piece of information: i have no problem sending this email, if it is unencrypted and unsigned. it only happens as soon as I either sign or encrypt the mail.

**Comment by dcbaker** [comment]
Ah python 2 and non-ascii. I think I can fix this, let's see how far down the rabbit trail we go.

**Comment by dcbaker** [comment]
This is going to be really hard to fix properly. I have a patch that fixes our side of the problem, but there's a problem in the way the python2 stdlib is implemented. It uses `cStringIO.StringIO` in the `email.generator` module, which is incapable of representing anything except ascii. I think I can do some ugly hacking to make it work correctly, but it's possible this wont work properly until we make the python3 transition.

**Comment by dcbaker** [comment]
I chased this issue down into the crypto module, and I still don't have it working. I had to monkey patch the email.generator module, because of the above, and ran into an issue in gpgme not supporting unicode characters. I think this bug may be best solved by porting to python 3. In the mean time the only work around I can come up with is to replace or remove non-ascii characters from filenames before encrypting, which is also pretty ugly.

**Comment by pazz** [comment]
Thanks for the input guys!

How about marking this as "wontfix", document a work-around somewhere
and move forward with a python3 port?

**Comment by dcbaker** [comment]
That sounds like a workable plan to me.

**Comment by pazz** [comment]
Can this be closed now that the python3 port was merged?
