### ISSUE TITLE
alot crashes on :remove

### ISSUE THREAD

**Issue by pdigiglio** [pazz/alot#1049]
When I use the `:remove` command in thread mode, _alot_ prints this message and hangs:
```python
Traceback (most recent call last):
  File "/usr/bin/alot", line 11, in <module>
    load_entry_point('alot==0.5.1', 'console_scripts', 'alot')()
  File "/usr/lib/python2.7/site-packages/alot/__main__.py", line 128, in main
    UI(dbman, cmdstring)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
    callback()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/lib/python2.7/site-packages/alot/buffers.py", line 381, in render
    msg = self.get_selected_message()
  File "/usr/lib/python2.7/site-packages/alot/buffers.py", line 424, in get_selected_message
    return self.get_selected_messagetree()._message
  File "/usr/lib/python2.7/site-packages/alot/buffers.py", line 420, in get_selected_messagetree
    return self._nested_tree[self.body.get_focus()[1][:1]]
AttributeError: 'SolidFill' object has no attribute 'get_focus'
```
The message doesn't get deleted after I kill `alot` and restart it. The version I'm using is 0.5.1.

**Comment by pazz** [comment]
I believe this is a duplicate of issue #700 ?

Quoting pdigiglio (2017-05-29 12:06:36)

**Comment by pdigiglio** [comment]
Yes, you're right. I'll close this and refer to #700. Thanks!
