### ISSUE TITLE
Silent failure with XapianError due to invalid query

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1074]
I did this: `alot -d debug -l log search date:moday..` (notice the typo in mo*n*day) and was presented with *no* buffer. *No warnings, nothing.* (In `:pyshell` `ui.current_buffer is None` evaluates to `True`!) The logfile has this exception:
```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/luc/vcs/alot/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/luc/vcs/alot/alot/commands/globals.py", line 125, in apply
    sort_order=self.order))
  File "/home/luc/vcs/alot/alot/buffers.py", line 228, in __init__
    self.rebuild()
  File "/home/luc/vcs/alot/alot/buffers.py", line 260, in rebuild
    self.result_count = self.dbman.count_messages(self.querystring)
  File "/home/luc/vcs/alot/alot/db/manager.py", line 267, in count_messages
    return self.query(querystring).count_messages()
  File "/usr/lib/python2.7/site-packages/notmuch/query.py", line 204, in count_messages
    raise NotmuchError(status)
notmuch.errors.XapianError: 
```
The natural way to solve this might be to have the search command or the search buffer or the dbmanager handle this. Optially they should trigger a notification about the error.

`call_apply` (inside `alot.ui.UI.apply_command` line 678) on the other hand seems very general and there might be other possibilities where failures are hidden so maybe it is possible to detect that we are getting back a failed defered here?

**Comment by dcbaker** [comment]
Since it's happening in a `deferred` you'll need an errback to handle it correctly I think. This seems like the kind of error that just using `ui.notify` tot ell you that it failed is probably sufficient.

**Comment by pazz** [comment]
The problem seems to be that `notmuch.query.Query.count_messages` just raises a `NotmuchError` that it instantiates with the "XapianError" status and not with an additional message string (cf notmuch.errors.py line 89).
So we could just catch `XapianError`, e.g. in `alot.db.DBmanager.create_query`, and hardcode a message string that complains about a malformed query. I'd much rather fix the notmuchs bindings so that they report more than just the error status (encoded as the exception subclass)...
