### ISSUE TITLE
Alot sometimes hangs when opening an email thread

### ISSUE THREAD

**Issue by hsanson** [pazz/alot#1117]
Very rarely but when opening threads I get this trace and alot hangs there. I never closes and I have to kill it with -9 signal:

```
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from twisted>=10.2.0->alot)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted>=10.2.0->alot)
  Using cached hyperlink-17.3.0-py2.py3-none-any.whl
Requirement already satisfied: six in ./.local/lib/python2.7/site-packages (from configobj>=4.7.0->alot)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from zope.interface>=3.6.0->twisted>=10.2.0->alot)
Requirement already satisfied: attrs in ./.local/lib/python2.7/site-packages (from Automat>=0.3.0->twisted>=10.2.0->alot)
Building wheels for collected packages: urwidtrees, twisted, configobj, pygpgme
  Running setup.py bdist_wheel for urwidtrees ... done
  Stored in directory: /home/ryujin/.cache/pip/wheels/38/0c/d9/947acb695052ee20f0cc2b7112e50916a1d4a6f538b2010b99
  Running setup.py bdist_wheel for twisted ... done
  Stored in directory: /home/ryujin/.cache/pip/wheels/57/08/00/28a9a86f0ee9f54260fb5949aed2e69b0425e8a878757aa7ce
  Running setup.py bdist_wheel for configobj ... done
  Stored in directory: /home/ryujin/.cache/pip/wheels/87/76/48/1564f8466fbd36402af5ac4972ffb56a6ef7f143892ef57fe5
  Running setup.py bdist_wheel for pygpgme ... done
 Traceback (most recent call last):/.cache/pip/wheels/34/c8/98/b4df6b7c12bd5c120cd6d7bc46e6781f2b48e235b52c472bca
  File "/home/ryujin/.local/bin/alot", line 11, in <module>
    sys.exit(main())
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/__main__.py", line 186, in main
    UI(dbman, cmdstring)
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/ui.py", line 92, in __init__
    self.mainloop.run()
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
    callback()
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/ryujin/.local/lib/python2.7/site-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/buffers.py", line 379, in render
    msg = self.get_selected_message()
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/buffers.py", line 422, in get_selected_message
    return self.get_selected_messagetree()._message
  File "/home/ryujin/.local/lib/python2.7/site-packages/alot/buffers.py", line 418, in get_selected_messagetree
    return self._nested_tree[self.body.get_focus()[1][:1]]
AttributeError: 'ThreadBuffer' object has no attribute '_nested_tree'

```

I use alot installed via pip in Ubuntu 16.04 LTS:

```
alot (0.4)                        - Terminal MUA using notmuch mail
  INSTALLED: 0.4 (latest)
```

**Comment by dcbaker** [comment]
This is a fairly old version of alot. 0.5.1 is current and were preparing
for a 0.6 release. Can you replicate this with either 0.5.1 or git master?

I'm on mobile, please excuse autocorrect fail.

**Comment by hsanson** [comment]
Fair enough... I installed latest version from git master. I will re-open this issue if it happens again.

BTW: I had to install swig2.0 package via apt-get to get alot to install. Docs should be updated.

**Comment by dcbaker** [comment]
Swig is required by python gpg. If you have gpgme >1.8 python bindings from
your distribution you don't need swig (well, your distribution will pull in
swig)

I'm on mobile, please excuse autocorrect fail.
