### ISSUE TITLE
cannot open thread: HeaderParseError ?

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1141]
Software Versions
-----------------

Alot version (either a number or sha for master): 0.6 7e706242

Observed behavior
-----------------

If I open a particular thread using `select`, nothing happens apparently. The log says

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 319, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 308, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/commands/search.py", line 40, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/buffers.py", line 344, in __init__
    self.rebuild()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/buffers.py", line 372, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 356, in __init__
    accumulate(msg)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 335, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 175, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 202, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 258, in _get_headers
    headers)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/widgets/thread.py", line 293, in construct_header_pile
    dvalue = decode_header(value, normalize=normalize)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.6-py2.7.egg/alot/db/utils.py", line 415, in decode_header
    valuelist = email.header.decode_header(value)
  File "/usr/lib/python2.7/email/header.py", line 108, in decode_header
    raise HeaderParseError
email.errors.HeaderParseError: 
```

**Comment by pazz** [comment]
I should say that the same occurs on current master.

**Comment by dcbaker** [comment]
Hmmmmm. does this email work in 0.5.1? I looked through the git history and it really doesn't look like much has changed in decode_header and friends.

**Comment by pazz** [comment]
I'll disect this myself soon and will find the offending header hopefully. stay tuned :-)

**Comment by pazz** [comment]
arg. I did not take a note which mail I used to trigger this one and cannot reproduce it any more. Sorry for the noise, I'll reopen if it happens again.
