### ISSUE TITLE
Packaging of alot-0.6 in Gentoo

### ISSUE THREAD

**Issue by GuillaumeSeren** [pazz/alot#1175]
Hey there !

I am packaging alot-0.6 for Gentoo, and I have trouble with the GPG support.

I have successfully change the dependency from 'dev-python/pygpgme' to 'app-crypt/gpgme',
and I have a few issue, and I am not sure that it comes from config file or the package itself.

Here the PR of the alot-0.6 ebuild: https://github.com/gentoo/gentoo/pull/6153

* Signing require to give a key name of to use a gpg_key value in the config.
* Encrypt do not work with the following error:
```
DEBUG:globals:CMDLINE: encrypt        
DEBUG:ui:envelope command string: "encrypt "                                 
DEBUG:__init__:mode:envelope got commandline "encrypt "                      
DEBUG:__init__:ARGS: [u'encrypt']     
DEBUG:__init__:cmd parms {'action': 'encrypt', 'trusted': False, 'keyids': []}                                                                             
DEBUG:utils:encryption keys: [u'serendev@gmail.com']                         
ERROR:ui:Traceback (most recent call last):                                  
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator                                                       
    return _inlineCallbacks(None, gen, Deferred())                           
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks                                                      
    result = g.send(result)           
  File "/usr/lib64/python2.7/site-packages/alot/commands/utils.py", line 46, in set_encrypt                                                                
    signed_only=signed_only)          
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator                                                       
    return _inlineCallbacks(None, gen, Deferred())                           
--- <exception caught here> ---       
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks                                                      
    result = g.send(result)           
  File "/usr/lib64/python2.7/site-packages/alot/commands/utils.py", line 76, in _get_keys                                                                  
    signed_only=signed_only)          
  File "/usr/lib64/python2.7/site-packages/alot/crypto.py", line 76, in get_key                                                                            
    if e.getcode() == gpg.errors.AMBIGUOUS_NAME:                             
exceptions.AttributeError: 'module' object has no attribute 'AMBIGUOUS_NAME'
```

Maybe I forget something, in the packaging or there is something wrong in my config,
I will try to reproduce the issue on master.
I asked on IRC and @pazz suggested I open a issue,
thank you for helping 🍻 

Software Versions
-----------------
Python 2.7.14
notmuch 0.25.2 
Alot version (either a number or sha for master):
alot-0.6 (7e70624)

**Comment by dcbaker** [comment]
What version of gpg do you have?

**Comment by GuillaumeSeren** [comment]
@dcbaker 
app-crypt/gpgme-1.8.0-r3
```
└─> gpg --version                                                                                                                                      |─┘
gpg (GnuPG) 2.2.0
libgcrypt 1.8.1                                                                                                                                           
Copyright (C) 2017 Free Software Foundation, Inc.                                                                                                         
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>                                                                            
This is free software: you are free to change and redistribute it.                                                                                        
There is NO WARRANTY, to the extent permitted by law.                                                                                                     
                                                                                                                                                          
Home: /home/gseren/.gnupg                                                                                                                                 
Supported algorithms:                                                                                                                                     
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA                                                                                                                 
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,                                                                                        
        CAMELLIA128, CAMELLIA192, CAMELLIA256                                                                                                             
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224                                                                                                     
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by dcbaker** [comment]
I'm sorry, I mean gpgme. :/

**Comment by GuillaumeSeren** [comment]
@dcbaker no problem 🍺 
```
└─> gpgme-tool --version                                                                                                                               |─┘
gpgme-tool 1.8.0                                                                                                                                          
Copyright (C) 2015 g10 Code GmbH                                                                                                                          
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/>                                                                                     
This is free software: you are free to change and redistribute it.                                                                                        
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by dcbaker** [comment]
hmmm, that should all be new enough. I'll poke at it later. I think my gentoo system is so out of date that it needs to be rebuilting using the world file.

**Comment by GuillaumeSeren** [comment]
Hey there,
I've been using alot-0.6 but I have yet fixed the issue, I will try to bump gpgme as well to check if it is the source of the problem.

If any of you, have some idea or test I'll take it ! 👍

**Comment by GuillaumeSeren** [comment]
Hey ! 🍺 
I've finally find out that the issue come from gpgme-1.8.0, and ':encrypt' & ':decrypt' works fine with gpgme-1.9.0.

Maybe it should be in the documentation right ?

**Comment by GuillaumeSeren** [comment]
I have confirmed that the gpgme-1.9.0 is the minimal working version,
so I upgraded the docs and open a PR for that, maybe some might find it useful.

**Comment by GuillaumeSeren** [comment]
We can close this issue thank you all for the feedback.
