### ISSUE TITLE
cannot reply to messages that match alias_regexp but not aliases

### ISSUE THREAD

**Issue by vrs** [pazz/alot#1177]
Steps to reproduce:
1. locate an email that's sent to an address of yours that matches your alias_regexp, but is not your address or among the aliases.
2. hit r for reply (or do :reply)

Results: Nothing happens. With verbose logging, alot logs:
```
DEBUG:ui:Got key (['r'], [114])
DEBUG:ui:cmdline: 'reply'
DEBUG:ui:thread command string: "reply"
DEBUG:__init__:mode:thread got commandline "reply"
DEBUG:__init__:ARGS: [u'reply']
DEBUG:__init__:cmd parms {'spawn': None, 'all': False, 'listreply': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:utils:unquoted header: |[snip]|
DEBUG:thread:candidate addresses: [('[snip]', '[snip]')]
DEBUG:thread:candidate addresses: [('[snip]', '[snip]')]
DEBUG:thread:candidate addresses: []
DEBUG:thread:candidate addresses: []
DEBUG:thread:candidate addresses: [('', 'vrs+label@synkretie.net')]
DEBUG:thread:match!: 'vrs+label@synkretie.net' 'vrs\+.+@synkretie.net'
DEBUG:thread:using realname: "vrs"
DEBUG:thread:using address: vrs+label@synkretie.net
DEBUG:thread:reply to: [snip]
DEBUG:utils:unquoted header: |[snip]|
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/user/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 679, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/commands/globals.py", line 819, in apply
    account = settings.get_account_by_address(addr)
  File "/home/user/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/settings/manager.py", line 454, in get_account_by_address
    raise NoMatchingAccount
alot.settings.errors.NoMatchingAccount: 
```
Expected: to be able to reply.

Versions affected: at least 0.6 from apt and current master (5bbe084d) from git.

Workaround: comment out alias_regexp in your config and set your From: address by hand.

Problems:
1. ComposeCommand doesn't check for exceptions from get_account_by_address (neither does utils.py, by the way)
2. get_account_by_address shouldn't be called in the first place - determine_sender already does all the work and has working alias_regexp support. But in both ReplyCommand and ForwardCommand, the account is thrown away and only the address is kept - which makes get_account_by_address fail. If the account was kept and then passed as an argument, things would work and most if not all(?) calls to get_account_by_address could be avoided, resulting in code savings as well.

I would've submitted a PR myself, but I couldn't decide how to pass the account and it seems like a deeper architectural issue - should it be part of Envelope or simply an extra argument? Or something else entirely?

**Comment by vrs** [comment]
see also: #1107

**Comment by pazz** [comment]
Hi welcome and thanks for the detailed bugreport.

I've had a hard time reproducing this due to hardcoded detection of "reply to mails from myself", but I can reproduce it now. One needs to have `reply_force_address` set to False to reproduce, which I hadn't.

Anyway, yes https://github.com/pazz/alot/blob/master/alot/commands/thread.py#L397 already determines the sending account and it chould be re-used instead of thrown away.
As you say, one solution is to hand the "sender" over to ComposeCommand, or Envelope, as a pair `(address-string, Account)`.
The alternative would be to keep this part as is, and replace the call to `account_by_address` within `envelope.SendCommand` by something that also takes the aliases into account. Maybe the latter option is the least intrusive, if one simply extends `settings.account_by_address` appropriately.
