### ISSUE TITLE
Implement GPG group feature

### ISSUE THREAD

**Issue by varac** [pazz/alot#1201]
Software Versions
-----------------

Python version: 2.7.14

Notmuch version: 0.25.1

Alot version (either a number or sha for master): 0.7rc1

Observed behavior
-----------------

I want to use the GPG group feature which allows defining an alias for a group of recipients to encrypt to.
I.e. I can put this into gpg.conf:

```
group admins@my.domain = fingerprint_alice fingerprint_bob fingerprint_eve
```

Then I can send a mail to admins@my.domain which should get automatically encrypted to Alice, Bob and Eve.
Thunderbird+Enigmail can do this but alot fails:

```
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 681, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/commands/envelope.py", line 214, in apply
    self.mail = self.envelope.construct_mail()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/db/envelope.py", line 238, in construct_mail
    self.encrypt_keys.values())
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/crypto.py", line 169, in encrypt
    assert keys, 'Must provide at least one key to encrypt with'
exceptions.AssertionError: Must provide at least one key to encrypt with

```

Here's a longer log: 
[alot.txt](https://github.com/pazz/alot/files/1720008/alot.txt)

Expected behavior
-----------------

Alot should instead encrypt the mail to all recipients and send it just fine.

**Comment by varac** [comment]
This is the neomutt issue about [Use of gpg's group option](https://github.com/neomutt/neomutt/issues/404) with some context/discussion around it.

**Comment by Hasimir** [comment]
I eventually got around to implementing my own suggestion for Mutt and Neomutt as referenced in that other issue.  That was posted to their user mailing lists a couple of weeks or so ago.

Since alot uses the GPGME Python bindings directly, the solution here was even more relevant for the main purpose of these examples and so I did that too.  Take your pick of:

 1. [Encrypt to Group](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=lang/python/examples/howto/encrypt-to-group.py;h=84f8d103596f49a1d7d326bac5797c1168695231;hb=HEAD), main version.
 2. [Encrypt to Group: Gullible Version](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=lang/python/examples/howto/encrypt-to-group-gullible.py;h=7ebfb6bcab19cf9530801cdbf03cc5c1ba096f36;hb=HEAD).
 3. [Encrypt to Group: Trust No One](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=lang/python/examples/howto/encrypt-to-group-trustno1.py;h=736c5f10b6069499c44a604063f1a57322fb39a4;hb=HEAD).

All three of those examples have just been committed to master, so if you want to wait for the next stable release, they'll be included with it.

There is no documentation for them just yet, but I expect I'll add that a bit later.  Not that it needs much; it's just taking a list of key IDs and preparing them in the right format for setting as recipients for GPGME to encrypt to.

Anyway, one of those should be able to be either dropped straight into this project as a solution or possibly with some minor adjustments (aside from those needed to change the input and output from files to email content, of course).

**Comment by varac** [comment]
@Hasimir Thanks alot !

**Comment by Hasimir** [comment]
You're most welcome.  :)

I'm quite the fan of a non-sequitur solution to anything and having the opportunity to do it myself was just too difficult to resist.

Oh, my largest group line currently sits on two dozen keys and running the gullible version on that worked perfectly (on that list there's always something wrong with *at least* one of them).

I've also got about fifty group lines in my gpg.conf and the Mutt/Neomutt script turns that into an 10-12KB crypt-hooks.rc file in under a second.  Importing and exporting keys will be coming to `gpg.Context()` very soon too.  All the fun stuff is in the HOWTO and the specific examples designed for it, most of which are executable scripts.

If you (or the project team here) have any questions, just wander over to gnupg-users and/or gnupg-devel, depending on what it is, though my [email address](http://www.adversary.org/ben-key.asc) is in the HOWTO and all those scripts too.

**Comment by pazz** [comment]
great, thanks for the code @Hasimir. Where exaxtly do those versions differ and what would be the most appropriate varient for us here?

I think we won't need the prompt stuff and could pick the relevant for-loop and add it to `alot.db.envelope.construct_mail`. If anyone wants this feature badly enough to provide a PR I'd be happy to push this.

**Comment by Hasimir** [comment]
> great, thanks for the code @Hasimir. Where exaxtly do those versions differ and what would be the most appropriate varient for us here?

I think that would depend on the user actually.  The differences are, as the name of the third one hints at, in the trust model used when encrypting to a group of key IDs.

The first one tries to do things properly, but falls back on "trust-model always" if there's a problem.  The gullible version just goes straight to always trust and encrypts to every key in the group or list.  The _X-Files_ … er, I mean the paranoid version tries it properly and then removes keys that can't be encrypted to for whatever reason and then encrypts just to those it can, including based on the trust model.

If you have a look at the [HOWTO in the docs directory](https://dev.gnupg.org/source/gpgme/browse/master/lang/python/docs/GPGMEpythonHOWTOen.org) you'll see that all of them are just slightly more advanced versions of existing examples in the sections on encrypting to multiple people.

I've also got draft and very unofficial documentation on an external site which uses a very different source format and which is already in HTML for you (the official doc is an org-mode file and there appears to be a problem with babel and the examples currently).  Anyway, that draft documentation [is here](http://files.au.adversary.org/crypto/gpgme-python-howto/webhelp/index.html) and the specific bit of interest to you [is here](http://files.au.adversary.org/crypto/gpgme-python-howto/webhelp/index.html#howto/part04/encrypt-to-many.html) and in this case it is used in conjunction [with this](http://files.au.adversary.org/crypto/gpgme-python-howto/webhelp/index.html#howto/part06/group-lines.html).

You may find some easter eggs in there.  😉

> I think we won't need the prompt stuff and could pick the relevant for-loop and add it to alot.db.envelope.construct_mail. If anyone wants this feature badly enough to provide a PR I'd be happy to push this.

Yeah, the down side of example scripts, of course, but I figure most coders will modify their input for their own use case.  The key issue with those bindings is usually just making sure everything you feed the thing is a byte literal string and otherwise you should be fine.

Also, one of our aspiring GSoC candidates just contributed the key_import function (don't worry, he was supervised) and the export functions will be done soon (not by a student, though).

**Comment by Hasimir** [comment]
As mentioned here last week, both importing and exporting are now available in GPGME master, including secret key exporting.  The bindings have also been tested, and confirmed to work, with Python 3.7.
