### ISSUE TITLE
Can not read signed mail without signing gpg key

### ISSUE THREAD

**Issue by lucc** [pazz/alot#1205]
Software Versions
-----------------

Python version: 2.7.14

Notmuch version: 0.26

Alot version (either a number or sha for master): 0.7rc1-17-g35464e2c (current master)

Observed behavior
-----------------

I received an email that is encrypted to me and signed by my friend with a key that I don't have and he did not push to any keyserver yet. The email is shown in the search buffer and when I `:select` it it takes some time and then I get an error message. The log file has this corresponding exception:
```
INFO:search:open thread view for thread:0000000000004625: foo
DEBUG:utils:unquoted header: |foobar <foo@bar.baz>|
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/luc/vcs/alot/alot/ui.py", line 690, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/luc/vcs/alot/alot/commands/search.py", line 40, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/luc/vcs/alot/alot/buffers.py", line 341, in __init__
    self.rebuild()
  File "/home/luc/vcs/alot/alot/buffers.py", line 369, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 354, in __init__
    accumulate(msg)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 333, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 174, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 201, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 257, in _get_headers
    headers)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 271, in construct_header_pile
    mail = self._message.get_email()
  File "/home/luc/vcs/alot/alot/db/message.py", line 105, in get_email
    self._email = message_from_file(f)
  File "/home/luc/vcs/alot/alot/db/utils.py", line 245, in message_from_file
    _handle_encrypted(m, m)
  File "/home/luc/vcs/alot/alot/db/utils.py", line 174, in _handle_encrypted
    sigs, d = crypto.decrypt_verify(message.get_payload(1).get_payload())
  File "/home/luc/vcs/alot/alot/crypto.py", line 222, in decrypt_verify
    (plaintext, _, verify_result) = ctx.decrypt(encrypted, verify=True)
  File "/home/luc/.local/lib/python2.7/site-packages/gpg/core.py", line 347, in decrypt
    raise errors.BadSignatures(verify_result)
gpg.errors.BadSignatures: 1111111111111111: No public key

```

Expected behavior
-----------------

I would like to see the thread buffer with the encrypted email and a warning or pseudo header about the signature. I know that the email is not entirely broken because I can at least decrypt it manually:
```sh
$ notmuch search --output=files tread:0000000000004625 | xargs cat | gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: encrypted with RSA key, ID 1111111111111111
gpg: encrypted with 2048-bit RSA key, ID 5FD9B5B293A10167, created 2013-08-27
      "Lucas Hoffmann <l-m-h@web.de>"
Content-Type: multipart/mixed; boundary="xxx";
 protected-headers="v1"
From: fobar <foo@bar.baz>
To: l-m-h@web.de
Message-ID: <foooo@bar>
Subject: foo

--xxx
Content-Type: multipart/mixed; boundary="yyy"

--yyy
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

foo

--yyy--

--xxx--
gpg: Signature made Tue 20 Feb 2018 10:17:59 PM CET
gpg:                using RSA key 111111111111111
gpg:                issuer "foo@bar.baz"
gpg: requesting key 1111111111111111 from hkp server keys.gnupg.net
gpg: Can't check signature: No public key
```

**Comment by dcbaker** [comment]
Another place to catch that exception. We probably need to handle that specially inside an encrypted message.

**Comment by dcbaker** [comment]
@lucc, Can you look at #1158 and see if that fixes the problem for you?

**Comment by dcbaker** [comment]
And actually, I think this is a duplicate of #1157

**Comment by lucc** [comment]
Yes it is a duplicate, sorry I did not find this yesterday evening.

I have trouble testing this right now as my friend has since uploaded his key (actually I think it was just a sync problem between the keyserver he uploaded to and the keyserver I downloaded from).

I will try to reproduce this later.

**Comment by dcbaker** [comment]
No worries, I only realized myself when I started writing code and
remembered writing it already, lol.

I'm on mobile, please excuse autocorrect fail.
