### ISSUE TITLE
exceptions.AttributeError: 'MainLoop' object has no attribute 'idle_handle'

### ISSUE THREAD

**Issue by kyrias** [pazz/alot#1212]
Software Versions
-----------------

Python version: 2.7.14

Alot version (either a number or sha for master): dae920e245ab9a539907740f41fac4db3028abe3

urwid: 2.0.1

Observed behavior
-----------------

As of commit dae920e245ab9a539907740f41fac4db3028abe3, running something like the following command:

    alot compose --sender johannes@kyriasis.com --to bar --subject baz

Causes the following exception to be raised:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 709, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/commands/globals.py", line 336, in apply
    return ExternalCommand.apply(self, ui)
  File "/usr/lib/python2.7/site-packages/alot/commands/globals.py", line 287, in apply
    with ui.paused():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 375, in paused
    self.mainloop.stop()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 362, in stop
    self.event_loop.remove_enter_idle(self.idle_handle)
exceptions.AttributeError: 'MainLoop' object has no attribute 'idle_handle'
```

The commit before dae920e245ab9a539907740f41fac4db3028abe3 works properly.

Expected behavior
-----------------

Alot should start properly without an exception raised.

**Comment by lucc** [comment]
I can not reproduce this right now. Neither with urwid 1.3.1 nor with 2.0.1. Do you have multible versions of urwid or alot installed? What thread/editor/terminal related settings have you set in alots config file? I have these 
```
terminal_cmd = term -fe # my script, in the end runs `termite -e`
editor_in_thread = True
editor_spawn = True
```

**Comment by three-comrades** [comment]
I can reproduce this: Arch Linux, alot 0.7, urwid 2.0.1. I don't have any of the settings @lucc mentions in my config (which seems to mean `editor_in_thread=False`, `editor_spawn=False`).

Playing around, I don't get the crash with:

```
editor_in_thread = True
editor_spawn = True
terminal_cmd = "xterm -e"
```

But this raises the exception, as well:
```
editor_in_thread = False
editor_spawn = True
terminal_cmd = "xterm -e"
```

**Comment by kyrias** [comment]
I didn't have those set either, but if I do set them I end up getting the editor spawned in a new terminal window, but it's opened without any file, so the editor is useless..

Before things broke I just ran nvim without spawning a new terminal or thread.

**Comment by kyrias** [comment]
Oh, so it opens an empty editor because termite requires the full command to execute to be part of the same argument, while alot sends them as multiple arguments...
