### ISSUE TITLE
No results of search in parentheses gives an error

### ISSUE THREAD

**Issue by varac** [pazz/alot#1224]
Software Versions
-----------------

Python 2.7.14
notmuch 0.26
alot 0.7.0dev

Observed behavior
-----------------

When I do a search in parentheses (i.e. `search (tag:unread AND NOT tag:lists)`) AND the search result is none, alot displays an error (`NoneType' object has no attribute 'get_thread_id'`) and throws this traceback in the log:

```
DEBUG:globals:CMDLINE: search (tag:unread AND NOT tag:lists)
DEBUG:ui:search command string: "search (tag:unread AND NOT tag:lists)"
DEBUG:__init__:mode:search got commandline "search (tag:unread AND NOT tag:lists)"
DEBUG:__init__:ARGS: [u'search', u'(tag:unread', u'AND', u'NOT', u'tag:lists)']
DEBUG:__init__:cmd parms {'sort': None, 'query': [u'(tag:unread', u'AND', u'NOT', u'tag:lists)']}
DEBUG:manager:Worker process 8146 spawned
DEBUG:manager:Worker process 8146 exited successfully
DEBUG:walker:EMPTY PIPE
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 709, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/commands/globals.py", line 120, in apply
    ui.buffer_focus(to_be_focused)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 465, in buffer_focus
    posthook(ui=self, dbm=self.dbman, buf=buf, success=success)
  File "/home/varac/.config/alot/hooks.py", line 23, in post_buffer_focus
    tid = buf.focused_thread.get_thread_id()
exceptions.AttributeError: 'NoneType' object has no attribute 'get_thread_id'

DEBUG:ui:Got key (['window resize'], [])
```

When the search result returns at least one message everything is fine.

Expected behavior
-----------------

Alot should only display no results in the buffer, without showing and error. It also should fetch the exception and not run into a traceback.

**Comment by varac** [comment]
Weird, cannot reproduce it. Will investigate further.
