### ISSUE TITLE
Returning to empty search buffer throws an error

### ISSUE THREAD

**Issue by varac** [pazz/alot#1225]
Software Versions
-----------------

Python 2.7.14
notmuch 0.26
alot 0.7.0dev

Observed behavior
-----------------

Returning to an empty search buffer gives an `NoneType' object has no attribute 'get_thread_id` error.

Steps to reproduce:

- Start alot with `alot -c /tmp/null -d debug -l /tmp/alot.txt` 
- Do a search that returns no results, i.e. `search tag:unread AND tag:lists`
- Switch to previous buffer
- Return back to search buffer

```
DEBUG:globals:CMDLINE: search tag:unread AND tag:lists
DEBUG:ui:search command string: "search tag:unread AND tag:lists"
DEBUG:__init__:mode:search got commandline "search tag:unread AND tag:lists"
DEBUG:__init__:ARGS: [u'search', u'tag:unread', u'AND', u'tag:lists']
DEBUG:__init__:cmd parms {'sort': None, 'query': [u'tag:unread', u'AND', u'tag:lists']}
DEBUG:manager:Worker process 15146 spawned
DEBUG:manager:Worker process 15147 spawned
DEBUG:manager:Worker process 15146 exited successfully
DEBUG:manager:Worker process 15147 exited successfully
DEBUG:walker:EMPTY PIPE
DEBUG:ui:Got key (['shift tab'], [27, 91, 90])
DEBUG:ui:cmdline: 'bprevious'
DEBUG:ui:search command string: "bprevious"
DEBUG:__init__:mode:search got commandline "bprevious"
DEBUG:__init__:ARGS: [u'bprevious']
DEBUG:__init__:cmd parms {'offset': -1}
DEBUG:manager:Worker process 15154 spawned
DEBUG:manager:Worker process 15154 exited successfully
DEBUG:walker:EMPTY PIPE
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 709, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/commands/globals.py", line 503, in apply
    ui.buffer_focus(self.buffer)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 465, in buffer_focus
    posthook(ui=self, dbm=self.dbman, buf=buf, success=success)
  File "/home/varac/.config/alot/hooks.py", line 23, in post_buffer_focus
    tid = buf.focused_thread.get_thread_id()
exceptions.AttributeError: 'NoneType' object has no attribute 'get_thread_id'
```

Please include any tracebacks or error information in the log file that you
generated, as well as a description of the behavior. Please don't post the
whole log file blindly as it might contain sensitive information and might be
quite big. A traceback and ~10 lines before and after is probably sufficient.

Expected behavior
-----------------

Returning to an empty search buffer will not result in any error.

**Comment by dcbaker** [comment]
That's happening in your hooks I think, can you disabled your post_buffer_focus hook and see if you can still reproduce this?

**Comment by varac** [comment]
@dcbaker Thx, indeed this solved the problem. I was using the hook documented in the wiki to [save marked position in search buffer](https://github.com/pazz/alot/wiki/Contrib-Hooks#save-marked-position-in-search-buffer). After removing it I don't get any errors anymore returning to an empty buffer - but also the position in search buffer is not saved anymore :(

**Comment by dcbaker** [comment]
There's a missing "is not None" check in that hook. If you replace the
"hasattr" check with "getatrr(...) is not None" it should work.

I'm on mobile, please excuse autocorrect fail.

**Comment by varac** [comment]
@dcbaker I changed the line from  `if success and hasattr(buf, "focused_thread"):` to `if success and getattr(buf, "focused_thread") is not None:` but now I get:

```
$ alot -c /tmp/null -d debug -l /tmp/alot.txt
…
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 709, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/home/varac/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/commands/globals.py", line 127, in apply
    sort_order=self.order))
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 399, in buffer_open
    self.buffer_focus(buf)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 465, in buffer_focus
    posthook(ui=self, dbm=self.dbman, buf=buf, success=success)
  File "/home/varac/.config/alot/hooks.py", line 26, in post_buffer_focus
    if success and getattr(buf, "focused_thread") is not None:
exceptions.AttributeError: 'SearchBuffer' object has no attribute 'focused_thread'
…
```

**Comment by pazz** [comment]
i think you want `get_selected_thread` instead.

**Comment by pazz** [comment]
or rather use a default value in your call to `getattr`

**Comment by varac** [comment]
@pazz Thx for the hint! Anyway, it would be great if anybody could update the [save marked position in search buffer hook](https://github.com/pazz/alot/wiki/Contrib-Hooks#save-marked-position-in-search-buffer) in the wiki with a working example. As I'm new to alot and not python-literate it's hard for me to figure out how exactly the hook needs to get implemented - or implement #1071 and then we don't need to maintain the hook in the wiki anymore.

Anyhow, closing this because this issue here is closed.

**Comment by varac** [comment]
Updated the wiki with a working hook:
https://github.com/pazz/alot/wiki/Contrib-Hooks/543da3384e2ed150931000cd5696fc441fb30338

**Comment by pazz** [comment]
thank you!
