### ISSUE TITLE
unable to load hooks file

### ISSUE THREAD

**Issue by teto** [pazz/alot#1238]
DEBUG:manager:unable to load hooks file:/home/teto/.config/alot/hooks.py

Please run alot again with the options `-d debug -l log`.

Software Versions
-----------------

Python version: python-2.7.14/

Notmuch version:

Alot version (either a number or sha for master): 0.7 (I can try master if required but it's not straightforward to do here).

Observed behavior
-----------------
I am trying to call a hook defined in my config via 
```
[bindings] 
[[thread]]
a = call hooks.apply_patch(ui)
```
but it fails with
```
DEBUG:ui:Got key (['a'], [97])
DEBUG:ui:cmdline: 'call hooks.apply_patch(ui)'
DEBUG:ui:thread command string: "call hooks.apply_patch(ui)"
DEBUG:__init__:mode:thread got commandline "call hooks.apply_patch(ui)"
DEBUG:__init__:ARGS: [u'call', u'hooks.apply_patch(ui)']
DEBUG:__init__:cmd parms {'command': u'hooks.apply_patch(ui)'}
ERROR:globals:'NoneType' object has no attribute 'apply_patch'
Traceback (most recent call last):
  File "/nix/store/90vxv10hp0vcml0lg5wgra9sj1rsbzf6-python2.7-alot-0.7/lib/python2.7/site-packages/alot/commands/globals.py", line 388, in apply
    exec(self.command)
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'apply_patch'
DEBUG:buffers:Tbuffer: auto remove unread tag from msg?
DEBUG:buffers:Tbuffer: No, cursor on summary
```

My alot config is generated from a script hence some errors which should not be related to the error, I kept them just in case
```
INFO:utils:Unknown values were found in `/home/teto/.config/alot/config`. Please check for typos if a specified setting does not seem to work:
encrypt_by_default
sign_by_default
bindings: thread
DEBUG:manager:unable to load hooks file:/home/teto/.config/alot/hooks.py
DEBUG:manager:template directory: `/home/teto/.config/alot/templates`
DEBUG:manager:themes directory: `/home/teto/.config/alot/themes`
INFO:utils:Unknown values were found in `/home/teto/.config/alot/themes/solarized_dark`. Please check for typos if a specified setting does not seem to work:

```

My hooks file has the following permissions
`-rw-r--r-- 1 teto users 3270 04-25 15:34 /home/teto/.config/alot/hooks.py`

Expected behavior
-----------------
The line  `DEBUG:manager:unable to load hooks file:/home/teto/.config/alot/hooks.py` gives 0 explanation as to why. Loading the hooks into a linter seems ok https://transfer.sh/6PMRo/hooks.py.
I would hope to see the python error/stacktrace that caused the failure.

**Comment by pazz** [comment]
It seems that you have the same problem for the theme config and that
this is not specific to hooks at all. Configobject (the lib we use to parse the
config file) reports extra, unexpected entries in your config (e.g.
"encrypt_by_default"), but those are in fact in the spec.

Just speculating here, but this could be an encoding issue.
Can you check and report that?

  file --mime-encoding ~/.config/alot/config


Also, what is your configobj version?

  python -c "import configobj;print configobj.__version__"

**Comment by teto** [comment]
seems like the warnings 
```
INFO:utils:Unknown values were found in `/home/teto/.config/alot/config`. Please check for typos if a specified setting does not seem to work:
encrypt_by_default
sign_by_default
bindings: thread 
```
were LGTM since these are account specific ? alot just choke on these so I removed them.

```
INFO:utils:Unknown values were found in `/home/teto/.config/alot/config`. Please check for typos if a specified setting does not seem to work:
bindings: thread
```
with the following config

```
[bindings] 
# reload config
% = reload
/ = prompt search

	[[thread]]
	a = call hooks.apply_patch(ui)
	' ' = fold; untag unread; move next unfolded

```
I tried various things but they all seem to fail. I don't understand why since it seems close to the examples http://alot.readthedocs.io/en/latest/configuration/key_bindings.html

**Comment by pazz** [comment]
the "extra values" warning seems to be due to configobj considering [repeated vlues](https://configobj.readthedocs.io/en/latest/configobj.html#repeated-values) as extra apparently. This is is weird, but the warning is unproblematic.

**Comment by teto** [comment]
I opened an issue on configobj. I agree it's minor. I will close this a bit later, just need to check sthg.

**Comment by pazz** [comment]
Cheers!
