### ISSUE TITLE
Different encodings detected

### ISSUE THREAD

**Issue by varac** [pazz/alot#1257]
Software Versions
-----------------

Python version: 3.6.5

Notmuch version: 0.26

Alot version (either a number or sha for master): latest master from today (34bc46fd07f355df9b7a07c4f1dcab469a0a2346)

Observed behavior
-----------------

Never had this issue before, alot works fine for me until now.
When I try to open a specific mail (all other mails open fine for me), I can't open the mail and I get this error in the log:

```
DEBUG:ui:Got key (['enter'], [10])
DEBUG:ui:cmdline: 'select; fold *; unfold tag:unread'
DEBUG:ui:search command string: "select"
DEBUG:__init__:mode:search got commandline "select"
DEBUG:__init__:ARGS: ['select']
DEBUG:__init__:cmd parms {}
INFO:search:open thread view for thread:…: …
DEBUG:utils:unquoted header: …
DEBUG:helper:Encoding ascii with confidence 1.000000
DEBUG:helper:Encoding ascii with confidence 1.000000
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/ui.py", line 708, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/search.py", line 39, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/buffers/thread.py", line 35, in __init__
    self.rebuild()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/buffers/thread.py", line 63, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 199, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 255, in _get_headers
    headers)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 269, in construct_header_pile
    mail = self._message.get_email()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/message.py", line 104, in get_email
    self._email = utils.message_from_bytes(f.read())
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 286, in message_from_bytes
    return message_from_file(io.StringIO(helper.try_decode(bytestring)))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 246, in message_from_file
    _handle_encrypted(m, m)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 182, in _handle_encrypted
    n = message_from_bytes(d)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 286, in message_from_bytes
    return message_from_file(io.StringIO(helper.try_decode(bytestring)))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 240, in message_from_file
    _handle_signatures(m, m, p)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 135, in _handle_signatures
    helper.email_as_bytes(message.get_payload(0)),
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/helper.py", line 642, in email_as_bytes
    "different encodings detected: {}".format(charsets))
builtins.RuntimeError: different encodings detected: {'windows-1252', 'ascii'}
```
I noticed that from the same sender, there's even another mail that fails the same.
Here's the mail stripped from private stuff:

```
Content-Type: multipart/encrypted; boundary="Apple-Mail=_..."; protocol="application/pgp-encrypted";
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (Mac OS X Mail 7...)
Subject: ...
Content-Description: OpenPGP encrypted message
X-Mailer: Apple Mail (2...)

This is an OpenPGP/MIME encrypted message (RFC 2440 and 3156)
--Apple-Mail=_...
Content-Transfer-Encoding: 7bit
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME Versions Identification

Version: 1

--Apple-Mail=_...
Content-Transfer-Encoding: 7bit
Content-Disposition: inline;
	filename=encrypted.asc
Content-Type: application/octet-stream;
	name=encrypted.asc
Content-Description: OpenPGP encrypted message

-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

...
-----END PGP MESSAGE-----

--Apple-Mail=_...

```

Expected behavior
-----------------

I'd like to open and view the mail without errors.

**Comment by varac** [comment]
So it turned out that that both mails triggering this error contained attachments inside GPG-encrypted mails.

**Comment by pazz** [comment]
thanks for reporting this. Out of interest, do you find the string 'windows-1252' anywhere in (a content type header of) these mails? If not, we may need to work around incorrect default return values in the python email module.

**Comment by varac** [comment]
> do you find the string 'windows-1252' anywhere in (a content type header of) these mails ?

No, I can't.

> Oh: as a workaround, you may want to test to just remove the clause that raises the exception, and fall back to utf-8 as charset.

That worked, thx for the workaround!

**Comment by mjg** [comment]
If you like, try out my branch [message-from-bytes](https://github.com/mjg/alot/tree/message-from-bytes) as mentioned in #1253 . It uses a different way of determining the encoding (much more like alot used to do).

**Comment by pazz** [comment]
I'm quite sure this is unrelated. This code is about extracting plaintext mails from encrypted ones, and the issue is that this particular mail has an unexpected mix of encodings, which we never fully dealt with.
