### ISSUE TITLE
Exception on compose

### ISSUE THREAD

**Issue by alexshpilkin** [pazz/alot#1277]
**Describe the bug**
An exception is raised when I attempt to compose a new message. I’m unable to create a new message at all, though replying works.

**Software Versions**
- Python version: 3.6.6
- Notmuch version: 0.27
- Alot version: master (4cba47a,  2018-07-24T21:41:22Z)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start alot
2. Press ‘m’ or input “:compose”
3. Observe no new buffer and an error in the status area:

        'Address' object has no attribute 'encode'
        (check the log for details)

**Error Log**

Some configuration info:
```
alex@etranger:~$ echo $NOTMUCH_CONFIG
/home/alex/.config/notmuch/config
alex@etranger:~$ ls -lR .config/alot
.config/alot:
total 4
-rw-r--r-- 1 alex alex 1083 Jul 23 22:32 config
alex@etranger:~$ ls -lR .abook
ls: cannot access '.abook': No such file or directory
```
Relevant portion of alot’s log:
```
DEBUG:ui:Got key (['m'], [109])
DEBUG:ui:cmdline: 'compose'
DEBUG:ui:search command string: "compose"
DEBUG:__init__:mode:search got commandline "compose"
DEBUG:__init__:ARGS: ['compose']
DEBUG:__init__:cmd parms {'sender': None, 'template': None, 'tags': None, 'subject': None, 'to': None, 'cc': None, 'bcc': None, 'attach': None, 'omit_signature': False, 'spawn': None, 'rest': []}
DEBUG:envelope:TEMPLATE: None
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python3.6/site-packages/alot/ui.py", line 708, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3.6/site-packages/alot/commands/globals.py", line 821, in apply
    fromstring = email.utils.formataddr((a.realname, a.address))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
builtins.AttributeError: 'Address' object has no attribute 'encode'
```
See also the [full redacted log][1] and the configuration files for [alot][2] and [notmuch][3].

[1]: https://github.com/pazz/alot/files/2225777/log.txt
[2]: https://github.com/pazz/alot/files/2225778/alot-config.txt
[3]: https://github.com/pazz/alot/files/2225779/notmuch-config.txt

**Comment by pazz** [comment]
Thanks for the detailed bug report, and cheers for the quick fix dcbaker ;-)
