### ISSUE TITLE
UnicodeDecodeError with Python3

### ISSUE THREAD

**Issue by josch** [pazz/alot#1291]
Hi,

I'm using the current git master (I'm at 5c53edfba561a2ebdca2741c92405dbd69bd469c) with Python3. Which seemed to work fine until today where I got the following backtrace in a search result:

```
DEBUG:ui:global command string: "search -- tag:unread and tag:to-me and not tag:spam"
DEBUG:__init__:mode:global got commandline "search -- tag:unread and tag:to-me and not tag:spam"
DEBUG:__init__:ARGS: ['search', '--', 'tag:unread', 'and', 'tag:to-me', 'and', 'not', 'tag:spam']
DEBUG:__init__:cmd parms {'sort': None, 'query': ['--', 'tag:unread', 'and', 'tag:to-me', 'and', 'not', 'tag:spam']}
DEBUG:manager:Worker process 23126 spawned
DEBUG:manager:Worker process 23126 exited successfully
DEBUG:utils:unquoted header: |mundo ingenia <central@publingenia.club>|
ERROR:ui:Traceback (most recent call last):
  File "/tmp/alot/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/tmp/alot/alot/commands/globals.py", line 126, in apply
    sort_order=self.order))
  File "/tmp/alot/alot/ui.py", line 405, in buffer_open
    self.buffer_focus(buf)
  File "/tmp/alot/alot/ui.py", line 465, in buffer_focus
    self.update()
  File "/tmp/alot/alot/ui.py", line 656, in update
    self.mainloop.draw_screen()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/tmp/alot/alot/buffers/buffer.py", line 19, in render
    return self.body.render(size, focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 471, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 353, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 718, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 688, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 356, in calculate_visible
    focus_widget, focus_pos = self._body.get_focus()
  File "/tmp/alot/alot/walker.py", line 29, in get_focus
    return self._get_at_pos(self.focus)
  File "/tmp/alot/alot/walker.py", line 62, in _get_at_pos
    widget = self._get_next_item()
  File "/tmp/alot/alot/walker.py", line 75, in _get_next_item
    next_widget = self.containerclass(next_obj, **self.kwargs)
  File "/tmp/alot/alot/widgets/search.py", line 26, in __init__
    self.rebuild()
  File "/tmp/alot/alot/widgets/search.py", line 61, in rebuild
    self.structure[partname])
  File "/tmp/alot/alot/widgets/search.py", line 145, in build_text_part
    content = prepare_string(name, thread, maxw)
  File "/tmp/alot/alot/widgets/search.py", line 212, in prepare_string
    s = content(thread)
  File "/tmp/alot/alot/widgets/search.py", line 188, in prepare_content_string
    lastcontent = ' '.join(m.get_text_content() for m in msgs)
  File "/tmp/alot/alot/widgets/search.py", line 188, in <genexpr>
    lastcontent = ' '.join(m.get_text_content() for m in msgs)
  File "/tmp/alot/alot/db/message.py", line 273, in get_text_content
    return extract_body(self.get_email(), types=['text/plain'])
  File "/tmp/alot/alot/db/utils.py", line 468, in extract_body
    body_parts.append(string_sanitize(remove_cte(part, as_string=True)))
  File "/tmp/alot/alot/db/utils.py", line 418, in remove_cte
    return raw_payload.decode(enc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 4: invalid start byte
```

The email that triggers this is just some spam so I uploaded it so that you can reproduce the problem:

[spam.txt](https://github.com/pazz/alot/files/2262275/spam.txt)

**Comment by pazz** [comment]
I cannot reproduce this (see below). I'm on the master branches for both alot (4a6711865b154152d4978e8316727f4902de3e02) and notmuch (b0ebb19d79b2ca84fabd5e9daa082701df5dfa8b).
```
DEBUG:manager:Worker process 6017 exited successfully
DEBUG:utils:unquoted header: |mundo ingenia <central@publingenia.club>|
DEBUG:walker:EMPTY PIPE
DEBUG:ui:Got key (['enter'], [10])
DEBUG:ui:cmdline: 'select; fold *; move next tag:unread; unfold'
DEBUG:ui:search command string: "select"
DEBUG:__init__:mode:search got commandline "select"
DEBUG:__init__:ARGS: ['select']
DEBUG:__init__:cmd parms {}
INFO:search:open thread view for thread:000000000001685a: Conmutador, Telefonos y Internet Por el mismo costo
DEBUG:utils:unquoted header: |mundo ingenia <central@publingenia.club>|
DEBUG:utils:unquoted header: |josch@debian.org|
DEBUG:utils:unquoted header: |Conmutador, Telefonos y Internet Por el mismo costo|
DEBUG:thread:want tags header
DEBUG:utils:unquoted header: |Sun, 05 Aug 2018 01:13:58 +0000|
DEBUG:utils:unquoted header: |<85a891dda32cc7564992b86a37dbf438@soporteuno1.com>|
DEBUG:utils:unquoted header: |powerphplist.png|
DEBUG:utils:command: /usr/bin/w3m -I UTF-8 -dump -T text/html /tmp/3q9n9iay.html
DEBUG:utils:parms: ('text/html=', 'charset=UTF-8')
DEBUG:thread:Tbuffer: auto remove unread tag from msg?
DEBUG:thread:Tbuffer: No, cursor on summary
DEBUG:ui:thread command string: " fold *"
DEBUG:__init__:mode:thread got commandline " fold *"
DEBUG:__init__:ARGS: ['fold', '*']
DEBUG:__init__:cmd parms {'query': ['*'], 'visible': False}
DEBUG:thread:matching lines *...
DEBUG:thread:setting focus to ('85a891dda32cc7564992b86a37dbf438@soporteuno1.com', (0,)) 
DEBUG:thread:collapsed True
DEBUG:thread:display_source False
DEBUG:thread:display_all_headers False
DEBUG:thread:display_attachements True
DEBUG:thread:AHT None
DEBUG:thread:DHT <alot.widgets.thread.DictList object at 0x7f505c42c438>
DEBUG:thread:MAINTREE [(<MessageSummaryWidget selectable box/flow widget>, [(<alot.widgets.thread.DictList object at 0x7f505c42c438>, None), (<urwidtrees.tree.SimpleTree object at 0x7f505c42c390>, None), (<alot.widgets.thread.TextlinesList object at 0x7f505c43a9e8>, None)])]

```

**Comment by lucc** [comment]
I was able to reproduce this on current master (ac3129c8). You have to set `prefer_plaintext = True` in the config. The error log is this:
```
ERROR:ui:Traceback (most recent call last):
  File "/home/luc/vcs/alot/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/home/luc/vcs/alot/alot/commands/search.py", line 41, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/luc/vcs/alot/alot/buffers/thread.py", line 37, in __init__
    self.rebuild()
  File "/home/luc/vcs/alot/alot/buffers/thread.py", line 65, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 205, in _assemble_structure
    bodytree = self._get_body()
  File "/home/luc/vcs/alot/alot/widgets/thread.py", line 238, in _get_body
    bodytxt = self._message.accumulate_body()
  File "/home/luc/vcs/alot/alot/db/message.py", line 266, in accumulate_body
    bodytext = extract_body(eml)
  File "/home/luc/vcs/alot/alot/db/utils.py", line 468, in extract_body
    body_parts.append(string_sanitize(remove_cte(part, as_string=True)))
  File "/home/luc/vcs/alot/alot/db/utils.py", line 418, in remove_cte
    return raw_payload.decode(enc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 4: invalid start byte
```

**Comment by lucc** [comment]
I think it originates from line 44 of the raw mail file.

**Comment by pazz** [comment]
I believe one simple and dirty way to avoid such failures would be to hide them via `decode`s `errors` parameter:

```
return raw_payload.decode(enc, errors='ignore')
```

**Comment by lucc** [comment]
This indeed fixes the test from #1321. It is indeed dirty :)

**Comment by vjrj** [comment]
> return raw_payload.decode(enc, errors='ignore')

This works for me, thanks

**Comment by pazz** [comment]
I am not entirely comfortable with this hotfix but it's better than nothing for now.
Ultimately, we should think about updating `utils.remove_cte` properly.

**Comment by pazz** [comment]
#1344 contains the mentioned hotfix. It also adds a debug log message for this nasty case to distinguish it from successful decodings.

**Comment by josch** [comment]
I'm using 0.8 and my emails get rendered wrongly now.

Instead of "Übung" I now just read "bung" and instead of "vollständigkeit" it says "vollstndigkeit" or "knnte" instead of "könnte".

I assume the culprit is this "fix"?

**Comment by lucc** [comment]
I think you are right. Can you open a new bug report for that?

**Comment by pazz** [comment]
If it has, than this should appear explicitly in the logs as `Decoding failure: ..` triggered by [this new line](https://github.com/pazz/alot/blob/master/alot/db/utils.py#L450). Does it?
If so, then your mails are broken to the extend that libmagic cannot guestimate correctly.

**Comment by josch** [comment]
This is happening with a lot of emails, so even if this is a bug:

 - it happens so often that a lot should really be able to work around it or it becomes useless to me
 - it used to work correctly in the past

Here the relevant log entries when I open such a message:

```
DEBUG:utils:unquoted header: |showbin|
DEBUG:utils:Content-Transfer-Encoding: "8bit"
DEBUG:utils:assuming Content-Transfer-Encoding: 8bit
DEBUG:utils:Decoding failure: 'utf-8' codec can't decode byte 0xdf in position 18: invalid continuation byte
```

From the message header:

```
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
```

From the message body:

    hei=C3=9Ft? Mir fallen n=C3=A4mlich nur gute Gr=C3=BCnde dagegen ein

At position 18 (the one shown in the debug message) the email has a `=C3=9F` which is UTF-8 for `U+00DF` which is a `ß` which is in turn precisely the character I expect to be there. So why is my email not treated as utf8 even though it says so in the `Content-Type` header? Which other information would be useful?

**Comment by lucc** [comment]
I think I noticed a discrepancy between the source view of an email in alot and the plain file on disk for one of my mails. Maybe the problem is hidden somewhere before we enter `remove_cte()`. I will have time tomorrow to join the search for the problem.

**Comment by lucc** [comment]
@josch I opened #1360 to discuss the new problems you describe. A first test was added in #1359. If you have the time it would be helpful if you can provide minimal emails that produce the problem (I think the combination of content-transfer-encoding and content-type, including charset is of interest). We could add them to the test suite and try to figure out what is going wrong. The more test cases we can cover the better the end result of the fix I think.
