### ISSUE TITLE
ValueError: There may be at most 1 Content-Disposition headers in a message

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1297]
I cannot open a thread containing a forwarded message with (pdf) attachment.

**Software Versions**
- Python version: 3.6.5
- Alot version: master 

**To Reproduce**
1. forward a mail with attachments
2. open thread buffer for the new thread

**Error Log**
```
ERROR:ui:Traceback (most recent call last):
  File "/home/pazz/projects/alot/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/home/pazz/projects/alot/alot/commands/search.py", line 41, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/pazz/projects/alot/alot/buffers/thread.py", line 37, in __init__
    self.rebuild()
  File "/home/pazz/projects/alot/alot/buffers/thread.py", line 65, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 205, in _assemble_structure
    bodytree = self._get_body()
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 238, in _get_body
    bodytxt = self._message.accumulate_body()
  File "/home/pazz/projects/alot/alot/db/message.py", line 266, in accumulate_body
    bodytext = extract_body(eml)
  File "/home/pazz/projects/alot/alot/db/utils.py", line 474, in extract_body
    part.add_header('Content-Disposition', 'attachment; ' + cd)
  File "/usr/lib/python3.6/email/message.py", line 543, in add_header
    self[_name] = SEMISPACE.join(parts)
  File "/usr/lib/python3.6/email/message.py", line 408, in __setitem__
    "in a message".format(max_count, name))
ValueError: There may be at most 1 Content-Disposition headers in a message
```

**Comment by varac** [comment]
I also get the same error when I try to open a gpg encrypted mail:

```
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/search.py", line 41, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/buffers/thread.py", line 37, in __init__
    self.rebuild()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/buffers/thread.py", line 65, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 205, in _assemble_structure
    bodytree = self._get_body()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/widgets/thread.py", line 238, in _get_body
    bodytxt = self._message.accumulate_body()
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/message.py", line 266, in accumulate_body
    bodytext = extract_body(eml)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/db/utils.py", line 474, in extract_body
    part.add_header('Content-Disposition', 'attachment; ' + cd)
  File "/usr/lib/python3.6/email/message.py", line 543, in add_header
    self[_name] = SEMISPACE.join(parts)
  File "/usr/lib/python3.6/email/message.py", line 408, in __setitem__
    "in a message".format(max_count, name))
ValueError: There may be at most 1 Content-Disposition headers in a message

```
This is the mail as notmuch show displays it:

```
$ notmuch show thread:0000000000016a8b
Failed to decrypt part: no error explanation given

…

header{
…
header}

body{

part{ ID: 1, Content-type: multipart/encrypted

part{ ID: 2, Content-type: application/pgp-encrypted
Non-text part: application/pgp-encrypted

part}

part{ ID: 3, Filename: encrypted.asc, Content-type: application/octet-stream
Non-text part: application/octet-stream

part}

part}

body}

message}

```

**Comment by varac** [comment]
Python 3.6.5, alot from master just of now.

**Comment by varac** [comment]
I just picked an arbitrary commit in history to see if works for me until this is fixed, 3c0097c3 is the one I tried and I can open gpg encr. threads again.

**Comment by dcbaker** [comment]
I have some mail I can reproduce this with. I guess one of us just need to start bisecting.

**Comment by pazz** [comment]
I just did: it seems that the offending commit is cd032bca1c4b062e2ef660e77d438a15d58e891e.

**Comment by dcbaker** [comment]
I kinda had a feeling it would be that commit. I'll look into it a little later today.
