### ISSUE TITLE
UnicodeEncodeError when replying to a sender with Umlaut in the name

### ISSUE THREAD

**Issue by varac** [pazz/alot#1300]
**Describe the bug**

I try to reply to a mail which holds a german Umlaut in the senders name (not email-adr). Alot fails with below error.

**Software Versions**
- Python version: 3.6.5
- Alot version: master (536f39b058)

**To Reproduce**
Steps to reproduce the behaviour:
1. Recieve a mail with  a german Umlaut in the senders name
2. Try to reply
3. See error

**Error Log**

```
…
DEBUG:thread:Replying to own message, set recipients to: ['"Some Bödy <someboedy@gmail.com>"']
…
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/ui.py", line 709, in apply_command
    await cmd.apply(self)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/thread.py", line 239, in apply
    to = ', '.join(self.ensure_unique_address(recipients))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/thread.py", line 321, in ensure_unique_address
    urecipients = [formataddr((n, str(a))) for a, n in res.items()]
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/thread.py", line 321, in <listcomp>
    urecipients = [formataddr((n, str(a))) for a, n in res.items()]
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 10: ordinal not in range(128)

```

**Comment by varac** [comment]
Unfortunaty, this is still not fixed in Python 3 with latest master (see [closed UnicodeEncodeError issues](https://github.com/pazz/alot/issues?q=is%3Aissue+UnicodeEncodeError+is%3Aclosed) )

**Comment by pazz** [comment]
I cannot reproduce this.
I've also played around with `email.utils.formataddr`, and your string, and the only way i can trigger this error is to explicitly ask formataddr to encode as ascii:

```python
from email.utils import formataddr
formataddr('Some Bödy', '<someboedy@gmail.com>'))
'=?utf-8?q?Some_B=C3=B6dy?= <<someboedy@gmail.com>>'

formataddr(('Some Bödy', '<someboedy@gmail.com>'), 'ascii')
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/usr/lib/python3.6/email/utils.py in formataddr(pair, charset)
     93         try:
---> 94             name.encode('ascii')
     95         except UnicodeEncodeError:

UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 6: ordinal not in range(128)

During handling of the above exception, another exception occurred:

UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-30-1650ddf40d71> in <module>()
----> 1 formataddr(('Some Bödy', '<someboedy@gmail.com>'), 'ascii')

/usr/lib/python3.6/email/utils.py in formataddr(pair, charset)
     96             if isinstance(charset, str):
     97                 charset = Charset(charset)
---> 98             encoded_name = charset.header_encode(name)
     99             return "%s <%s>" % (encoded_name, address)
    100         else:

/usr/lib/python3.6/email/charset.py in header_encode(self, string)
    291         """
    292         codec = self.output_codec or 'us-ascii'
--> 293         header_bytes = _encode(string, codec)
    294         # 7bit/8bit encodings return the string unchanged (modulo conversions)
    295         encoder_module = self._get_encoder(header_bytes)

/usr/lib/python3.6/email/charset.py in _encode(string, codec)
    161         return string.encode('ascii', 'surrogateescape')
    162     else:
--> 163         return string.encode(codec)
    164 
    165 

UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 6: ordinal not in range(128)
```

... but of course we don't do that.

**Comment by varac** [comment]
Weird, I just tried with todays master and cannot reproduce this error neither. Sorry for the noise, will reopen if I encounter it again.
