### ISSUE TITLE
Exception: Unknown Content-Transfer-Encoding: "8bit "

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1325]
I have received a mail that fails to open from search buffer.

**Software Versions**
- Python version: 3.6.6
- Notmuch version: 0.27+54~gb0ebb19
- Alot version: 0.7 (master)

**The mailfile (ASCII encoded)**
```
Subject: 8bit
Date: Thu, 18 Oct 2018 01:11:11 +0100
From: UoE HR <corehr@example.ac.uk>
To: <me@example.ac.uk>
Content-Type: multipart/mixed; boundary="MIME.Bound"
Message-ID: <8bit-err@bhmhub2.example.ac.uk>
MIME-Version: 1.0
X-TUID: lzP+Z9yKxahe

--MIME.Bound
Content-Type: text/plain; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: 8bit 

Dear Colleague, 
This is a system generated email, please do not reply.


 
--MIME.Bound--

```

**log**
```
ERROR:ui:Traceback (most recent call last):
  File "/home/pazz/projects/alot/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/home/pazz/projects/alot/alot/commands/search.py", line 41, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/pazz/projects/alot/alot/buffers/thread.py", line 37, in __init__
    self.rebuild()
  File "/home/pazz/projects/alot/alot/buffers/thread.py", line 65, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 205, in _assemble_structure
    bodytree = self._get_body()
  File "/home/pazz/projects/alot/alot/widgets/thread.py", line 238, in _get_body
    bodytxt = self._message.accumulate_body()
  File "/home/pazz/projects/alot/alot/db/message.py", line 272, in accumulate_body
    bodytext = extract_body(eml)
  File "/home/pazz/projects/alot/alot/db/utils.py", line 475, in extract_body
    body_parts.append(string_sanitize(remove_cte(part, as_string=True)))
  File "/home/pazz/projects/alot/alot/db/utils.py", line 420, in remove_cte
    'Unknown Content-Transfer-Encoding: "{}"'.format(cte))
Exception: Unknown Content-Transfer-Encoding: "8bit "
```

**Comment by dcbaker** [comment]
that looks pretty easy to fix, just need to add `.strip()` call somewhere.
