### ISSUE TITLE
alot v0.8 still requires Twisted

### ISSUE THREAD

**Issue by ninewise** [pazz/alot#1349]
The mail announcing alot-v0.8 mentioned python-Twisted is no longer a dependency. While packaging for void linux, I found it's still mentioned in `setup.py` and `alot/__main__.py`. The import in the main file is used as far as I can tell.

**Software Versions**
- Python version: 3.6
- Alot version: 0.8 (release)

**Error Log when running without Twisted installed**
```
Traceback (most recent call last):
  File "/usr/bin/alot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'twisted>=10.2.0' distribution was not found and is required by alot
```

**Error Log when running with twisted removed from the requires.txt**
```
Traceback (most recent call last):
  File "/usr/bin/alot", line 11, in <module>
    load_entry_point('alot==0.8', 'console_scripts', 'alot')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/alot/__main__.py", line 19, in <module>
    from twisted.internet import asyncioreactor
ImportError: cannot import name 'asyncioreactor'
```

As discussed in IRC, according to e96adc4bafd72aee7380020a6e1f92a055358d86 it is indeed still a dependency.

**Comment by pazz** [comment]
You are right and I was a bit too hasty when I announced that we'd drop all twisted dependencies.
[For now we rely on urwids twisted reactor](https://github.com/pazz/alot/commit/e96adc4bafd72aee7380020a6e1f92a055358d86)  because [native urwid asyncio handling is faulty](https://en.wikipedia.org/wiki/Floating-point_arithmetic).

Bottom line: Do not drop the `twisted.internet` dependency yet in packages.
