### ISSUE TITLE
twisted reactor conflicts with asyncio

### ISSUE THREAD

**Issue by bebarino** [pazz/alot#1350]
Upon starting alot the initial_command of "search tag:inbox" doesn't show any results. Furthermore, upon sending an email the thread sending the email never returns. I also get a stracktrace when I quit, indicating that some tasks were never awaited.

For example, upon quitting the program I see this:

```Exception ignored in: <bound method Task.__del__ of <Task pending coro=<UI.apply_commandline() running at ~/.local/lib/python3.5/site-packages/alot-0.8-py3.5.egg/alot/ui.py:235>>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 92, in __del__
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1289, in call_exception_handler
  File "/usr/lib/python3.5/logging/__init__.py", line 1309, in error
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1488, in callHandlers
  File "/usr/lib/python3.5/logging/__init__.py", line 856, in handle
  File "/usr/lib/python3.5/logging/__init__.py", line 1048, in emit
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
NameError: name 'open' is not defined
/usr/lib/python3.5/asyncio/base_events.py:491: RuntimeWarning: coroutine 'UI.apply_commandline' was never awaited
```

I dug some more into the problem and it looks like we aren't telling twisted to use the asyncio event loop, but then we're creating tasks in the asyncio event loop that never get to run. Poking around on the internet I found [this post](https://meejah.ca/blog/python3-twisted-and-asyncio) that says we need to install the right event loop really early. So changing the asyncioreactor.install() call in alot/__main__.py to use asyncio.get_event_loop() instead of None makes things work better for me. I can get my initial command to display results and sending email also doesn't hang the UI and never return.

**Software Versions**
Python 3.5.3
notmuch 0.28+10~gbaa4185
alot 0.8
msmtp version 1.6.6

**Comment by pazz** [comment]
Thanks for reportin this. My lazy question for now is: Have you tried with python >= 3.6? Because if that'd work then we may just as well drop support for 3.5 downwards.

IIRC, the problem with `asyncio.get_event_loop()` etc. is that [urwids asyncio event loop handling](https://github.com/urwid/urwid/issues/90) is silly and this is an open problem on their side. See also #1302 and related here.

Nevertheless, I also suspect that we're not quite using twisted + asyncio right, as I occasionally see some unexpected (yet unreported, sorry) behaviour.

**Comment by bebarino** [comment]
> My lazy question for now is: Have you tried with python >= 3.6? Because if that'd work then we may just as well drop support for 3.5 downwards.

I'm using debian and it's not super simple to try python >= 3.6 without some gymnastics. I can try and see if I can figure it out and test it out though.

> IIRC, the problem with asyncio.get_event_loop() etc. is that urwids asyncio event loop handling is silly and this is an open problem on their side. See also #1302 and related here.

Right. Seems like a long standing problem. I don't see a high cpu usage on my system. Is there anything I can do to try and reproduce it with my fix?

> Nevertheless, I also suspect that we're not quite using twisted + asyncio right, as I occasionally see some unexpected (yet unreported, sorry) behaviour.

Yes I see another error when I quit the program

```
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 511, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 65, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 146, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

so probably there's more work to do to make the whole program await all the tasks.

**Comment by psic** [comment]
same issue here and same solution.
alot 0.8.1
python 3.7.2
