### ISSUE TITLE
Open upstream bug: string index out of range when opening threads with malformatted To, Cc, or BCC headers

### ISSUE THREAD

**Issue by MacGyverNL** [pazz/alot#1367]
**Describe the bug**
This bug report is only intended to document this as an ***open upstream bug***:
https://bugs.python.org/issue29412
https://github.com/python/cpython/pull/6907

When trying to open certain e-mails in thread view, alot errors with string index out of range. This is an IndexError in upstream's e-mail parser when passed an e-mail with certain types of formatting errors in the To, Cc, and Bcc headers that are otherwise accepted by mail servers.

**Software Versions**
- Python version: 3.7, apparently also present in earlier versions and still present in master branch.
- Alot version: 8

**To Reproduce**
Steps to reproduce the behaviour:
1. Have an e-mail with a To-header that looks like, e.g.
`To: Name <name@example.com>, `
Note there is a space after the comma.
2. Try to open the e-mail in thread view.
3. Alot errors with string index out of range. This is an IndexError in upstream's e-mail parser.

The issue at the time of writing is that in _header_value_parser.py of the email library, on lines 1339 and 1341, https://github.com/python/cpython/blob/master/Lib/email/_header_value_parser.py#L1339, no check is done to see whether after stripping leading tokens `value` is not an empty string.
Until upstream merges proposed patches, a quick fix is to manually change the local install of the library. Change statements on lines 1339 and 1341 to read
```
    if value and value[0]=='"':
        token, value = get_quoted_string(value)
    elif value and value[0] in SPECIALS:
```

**Comment by MacGyverNL** [comment]
Closing because, as mentioned, this is an upstream bug, not something alot should fix.

**Comment by bebarino** [comment]
The fix in that bug report doesn't work for me. I have a To header that looks like this:

  `To: unlisted-recipients:; (no To-header on input)`

and the upstream email library still fails. Can we move back to using the old compat32 policy instead of policy=email.policy.SMTP? Basically revert commit cd032bca1c4b062e2ef660e77d438a15d58e891e until upstream fixes the problem?

**Comment by MacGyverNL** [comment]
> The fix in that bug report doesn't work for me.

Which fix? The one I gave above, or (one of the) fixes in the upstream report? It's possible if mine doesn't work, that this is a separate issue.

> and the upstream email library still fails.

Could you check the logs and figure out on which line this happens? If it's not the same, open a separate issue; otherwise, I'll reopen this issue.

**Comment by bebarino** [comment]
> Which fix? The one I gave above, or (one of the) fixes in the upstream report? It's possible if mine doesn't work, that this is a separate issue.

Both.

> Could you check the logs and figure out on which line this happens? If it's not the same, open a separate issue; otherwise, I'll reopen this issue.

Right. I see this traceback after applying your fix mentioned above.

>   File "/usr/lib/python3.5/email/message.py", line 511, in get_all
    values.append(self.policy.header_fetch_parse(k, v))
  File "/usr/lib/python3.5/email/policy.py", line 160, in header_fetch_parse
    return self.header_factory(name, value)
  File "/usr/lib/python3.5/email/headerregistry.py", line 586, in __call__
    return self[name](name, value)
  File "/usr/lib/python3.5/email/headerregistry.py", line 197, in __new__
    cls.parse(value, kwds)
  File "/usr/lib/python3.5/email/headerregistry.py", line 344, in parse
    for mb in addr.all_mailboxes]))
  File "/usr/lib/python3.5/email/headerregistry.py", line 344, in <listcomp>
    for mb in addr.all_mailboxes]))
AttributeError: 'Group' object has no attribute 'local_part'

So I can open another issue for this.

**Comment by andir** [comment]
@bebarino  
> > File "/usr/lib/python3.5/email/message.py", line 511, in get_all
> > values.append(self.policy.header_fetch_parse(k, v))
> > File "/usr/lib/python3.5/email/policy.py", line 160, in header_fetch_parse
> > return self.header_factory(name, value)
> > File "/usr/lib/python3.5/email/headerregistry.py", line 586, in **call**
> > return self[name](name, value)
> > File "/usr/lib/python3.5/email/headerregistry.py", line 197, in **new**
> > cls.parse(value, kwds)
> > File "/usr/lib/python3.5/email/headerregistry.py", line 344, in parse
> > for mb in addr.all_mailboxes]))
> > File "/usr/lib/python3.5/email/headerregistry.py", line 344, in 
> > for mb in addr.all_mailboxes]))
> > AttributeError: 'Group' object has no attribute 'local_part'
> 
> So I can open another issue for this.

Did you ever find a solution for this? I am on python 3.7.6 that should have all the linked fixes but I am still seeing this. This really looks like a dedicated issue to me.

**Comment by pazz** [comment]
I have honestly not followed up on this. But from your log it looks like you're on python 3.5, not 3.7.6...

**Comment by andir** [comment]
> I have honestly not followed up on this. But from your log it looks like you're on python 3.5, not 3.7.6...

That log was part of the quotes message of @bebarino above.

Here is my log:

```
  ERROR:ui:Traceback (most recent call last):
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/ui.py", line 711, in apply_command
      cmd.apply(self)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/commands/search.py", line 41, in apply
      sb = buffers.ThreadBuffer(ui, self.thread)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/buffers/thread.py", line 37, in __init__
      self.rebuild()
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/buffers/thread.py", line 65, in rebuild
      self._tree = ThreadTree(self.thread)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 352, in __init__
      accumulate(msg)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 331, in accumulate
      self._message[mid] = MessageTree(msg, odd)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 172, in __init__
      self._maintree = SimpleTree(self._assemble_structure())
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 199, in _assemble_structure
      mainstruct.append((self._get_headers(), None))
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 255, in _get_headers
      headers)
    File "/nix/store/6fyd1hf6x0a2w95r91x9a15z286pnnwc-python3.7-alot-0.8.1/lib/python3.7/site-packages/alot/widgets/thread.py", line 283, in construct_header_pile
      values = mail.get_all(key)
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/message.py", line 510, in get_all
      values.append(self.policy.header_fetch_parse(k, v))
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/policy.py", line 163, in header_fetch_parse
      return self.header_factory(name, value)
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/headerregistry.py", line 589, in __call__
      return self[name](name, value)
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/headerregistry.py", line 197, in __new__
      cls.parse(value, kwds)
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/headerregistry.py", line 347, in parse
      for mb in addr.all_mailboxes]))
    File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/email/headerregistry.py", line 347, in <listcomp>
      for mb in addr.all_mailboxes]))
  AttributeError: 'Group' object has no attribute 'local_part'    
```

**Comment by MacGyverNL** [comment]
FWIW, this was a completely different error in a completely different source file, and @bebarino never seems to have opened another issue for it; rather, they mentioned it in the upstream backport pull request and seemed not to get a response to their particular issue. I haven't debugged this. Seems to have finally been reported upstream last December as https://bugs.python.org/issue39100 . Whatever the issue, it would be more useful to either take it there or open a separate issue about it.

**Comment by bebarino** [comment]
I'm on 3.7 but I think I'm still running into this problem. I see this sort of traceback:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/ui.py", line 710, in apply_command
    cmd.apply(self)
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/commands/search.py", line 43, in apply
    tb.unfold_matching(query)
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/buffers/thread.py", line 339, in unfold_matching
    MT.expand(MT.root)
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 209, in expand
    self.reassemble()
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 184, in reassemble
    self._maintree._treelist = self._assemble_structure()
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 220, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 276, in _get_headers
    headers)
  File "/usr/local/lib/python3.7/dist-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 304, in construct_header_pile
    values = mail.get_all(key)
  File "/usr/lib/python3.7/email/message.py", line 510, in get_all
    values.append(self.policy.header_fetch_parse(k, v))
  File "/usr/lib/python3.7/email/policy.py", line 163, in header_fetch_parse
    return self.header_factory(name, value)
  File "/usr/lib/python3.7/email/headerregistry.py", line 589, in __call__
    return self[name](name, value)
  File "/usr/lib/python3.7/email/headerregistry.py", line 197, in __new__
    cls.parse(value, kwds)
  File "/usr/lib/python3.7/email/headerregistry.py", line 347, in parse
    for mb in addr.all_mailboxes]))
  File "/usr/lib/python3.7/email/headerregistry.py", line 347, in <listcomp>
    for mb in addr.all_mailboxes]))
AttributeError: 'Group' object has no attribute 'local_part'
```

I upgraded to the latest master commit 27c4aaddecf8a877b197be4fbe607678539b2513 and it still fails the same way.

**Comment by bebarino** [comment]
I'm still hitting this on python 3.8, but I see that the python bug hasn't gone anywhere, so that's to be expected. For now I'm still hacking the python library myself to use getattr() instead of accessing mb directly. If I can figure out how to update the bug upstream then I'll send this simple patch along. With it applied I see "unlisted-recipients <>" in the UI.

```
--- /usr/lib/python3.8/email/headerregistry.py.orig 
+++ /usr/lib/python3.8/email/headerregistry.py 
@@ -347,8 +347,8 @@
             for addr in address_list.addresses:
                 groups.append(Group(addr.display_name,
                                     [Address(mb.display_name or '',
-                                             mb.local_part or '',
-                                             mb.domain or '')
+                                             getattr(mb, 'local_part', ''),
+                                             getattr(mb, 'domain', ''))
                                      for mb in addr.all_mailboxes]))
             defects = list(address_list.all_defects)
         else:
```
