### ISSUE TITLE
Exception raised when mail with expired key is in the results.

### ISSUE THREAD

**Issue by josch** [pazz/alot#1377]
Hi, I'm using alot 0.8 from Debian and when a thread with an expired gpg key is in the search results I am getting the following exception:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/share/alot/alot/crypto.py", line 261, in _decrypt_verify_with_context
    encrypted, verify=True)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 432, in decrypt
    raise errors.BadSignatures(verify_result, results=results)
gpg.errors.BadSignatures: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: Key expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/alot/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/usr/share/alot/alot/commands/globals.py", line 126, in apply
    sort_order=self.order))
  File "/usr/share/alot/alot/ui.py", line 405, in buffer_open
    self.buffer_focus(buf)
  File "/usr/share/alot/alot/ui.py", line 465, in buffer_focus
    self.update()
  File "/usr/share/alot/alot/ui.py", line 656, in update
    self.mainloop.draw_screen()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/share/alot/alot/buffers/buffer.py", line 19, in render
    return self.body.render(size, focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 471, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 353, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 718, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 688, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 356, in calculate_visible
    focus_widget, focus_pos = self._body.get_focus()
  File "/usr/share/alot/alot/walker.py", line 29, in get_focus
    return self._get_at_pos(self.focus)
  File "/usr/share/alot/alot/walker.py", line 62, in _get_at_pos
    widget = self._get_next_item()
  File "/usr/share/alot/alot/walker.py", line 75, in _get_next_item
    next_widget = self.containerclass(next_obj, **self.kwargs)
  File "/usr/share/alot/alot/widgets/search.py", line 26, in __init__
    self.rebuild()
  File "/usr/share/alot/alot/widgets/search.py", line 61, in rebuild
    self.structure[partname])
  File "/usr/share/alot/alot/widgets/search.py", line 145, in build_text_part
    content = prepare_string(name, thread, maxw)
  File "/usr/share/alot/alot/widgets/search.py", line 213, in prepare_string
    s = content(thread)
  File "/usr/share/alot/alot/widgets/search.py", line 188, in prepare_content_string
    lastcontent = ' '.join(m.get_text_content() for m in msgs)
  File "/usr/share/alot/alot/widgets/search.py", line 188, in <genexpr>
    lastcontent = ' '.join(m.get_text_content() for m in msgs)
  File "/usr/share/alot/alot/db/message.py", line 281, in get_text_content
    return extract_body(self.get_email(), types=['text/plain'])
  File "/usr/share/alot/alot/db/message.py", line 111, in get_email
    f.read(), self._session_keys)
  File "/usr/share/alot/alot/db/utils.py", line 302, in decrypted_message_from_bytes
    session_keys)
  File "/usr/share/alot/alot/db/utils.py", line 261, in decrypted_message_from_message
    _handle_encrypted(m, m, session_keys)
  File "/usr/share/alot/alot/db/utils.py", line 177, in _handle_encrypted
    sigs, d = crypto.decrypt_verify(payload, session_keys)
  File "/usr/share/alot/alot/crypto.py", line 226, in decrypt_verify
    return _decrypt_verify_with_context(ctx, encrypted)
  File "/usr/share/alot/alot/crypto.py", line 266, in _decrypt_verify_with_context
    (plaintext, _, _) = ctx.decrypt(encrypted, verify=False)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 431, in decrypt
    for s in verify_result.signatures):
AttributeError: 'NoneType' object has no attribute 'signatures'
```

As a result, nothing is shown and the error is also not propagated to the ui.

**Comment by aepsil0n** [comment]
I did some digging… there is an issue with the GPGme Python wrapper. The `verify=False` flag is incorrectly flipped in the decrypt method. There is already an [upstream fix](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=shortlog;h=refs/heads/dkg/fix-T4271) on a feature branch that should address this issue eventually.

**Comment by varac** [comment]
Similar issue with a mail containing a gpg signature from a key that is missing in the keyring:

```
DEBUG:utils:Content-Transfer-Encoding: "7bit"
DEBUG:utils:assuming Content-Transfer-Encoding: 7bit
DEBUG:utils:Content-Transfer-Encoding: "7bit"
DEBUG:utils:assuming Content-Transfer-Encoding: 7bit
DEBUG:utils:Content-Transfer-Encoding: "quoted-printable"
DEBUG:utils:assuming Content-Transfer-Encoding: quoted-printable
DEBUG:utils:Content-Transfer-Encoding: "7bit"
DEBUG:utils:assuming Content-Transfer-Encoding: 7bit
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/crypto.py", line 261, in _decrypt_verify_with_context
    encrypted, verify=True)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 432, in decrypt
    raise errors.BadSignatures(verify_result, results=results)
gpg.errors.BadSignatures: <FINGERPRINT REDACTED>: No public key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/ui.py", line 711, in apply_command
    cmd.apply(self)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/commands/search.py", line 41, in apply
    sb = buffers.ThreadBuffer(ui, self.thread)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/buffers/thread.py", line 37, in __init__
    self.rebuild()
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/buffers/thread.py", line 73, in rebuild
    self._tree = ThreadTree(self.thread)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 352, in __init__
    accumulate(msg)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 343, in accumulate
    odd = accumulate(reply, odd)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 343, in accumulate
    odd = accumulate(reply, odd)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 343, in accumulate
    odd = accumulate(reply, odd)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 331, in accumulate
    self._message[mid] = MessageTree(msg, odd)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 172, in __init__
    self._maintree = SimpleTree(self._assemble_structure())
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 199, in _assemble_structure
    mainstruct.append((self._get_headers(), None))
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 255, in _get_headers
    headers)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/widgets/thread.py", line 269, in construct_header_pile
    mail = self._message.get_email()
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/db/message.py", line 111, in get_email
    f.read(), self._session_keys)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/db/utils.py", line 302, in decrypted_message_from_bytes
    session_keys)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/db/utils.py", line 261, in decrypted_message_from_message
    _handle_encrypted(m, m, session_keys)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/db/utils.py", line 177, in _handle_encrypted
    sigs, d = crypto.decrypt_verify(payload, session_keys)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/crypto.py", line 226, in decrypt_verify
    return _decrypt_verify_with_context(ctx, encrypted)
  File "/home/varac/.local/lib/python3.7/site-packages/alot-0.8.1-py3.7.egg/alot/crypto.py", line 266, in _decrypt_verify_with_context
    (plaintext, _, _) = ctx.decrypt(encrypted, verify=False)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 431, in decrypt
    for s in verify_result.signatures):
AttributeError: 'NoneType' object has no attribute 'signatures'

DEBUG:ui:search command string: " fold *"
DEBUG:__init__:mode:search got commandline " fold *"
DEBUG:__init__:ARGS: ['fold', '*']
DEBUG:__init__:unknown command: fold

```
