### ISSUE TITLE
Requesting non-existant theming attribute raises an Exception

### ISSUE THREAD

**Issue by Nelyah** [pazz/alot#1440]
I am trying to develop a new feature and need to access theme attribute through the `alot.settings.get_theming_attribute()` function. 

This function calls the function `alot.settings.theme.Theme.get_attribute()`. The latter tries to access the config with 

    thmble = self._config[mode][name]

without first checking for non-existant value (if `mode` or `name` are present). If the attribute is not present, there will be an exception raised. This could easily be fixed by adding 

        if not mode in self._config or name not in self._config[mode]:
            return None
        thmble = self._config[mode][name]

before trying to access the config. Is raising an exception an expected behaviour? Shouldn't we instead return None?

Edit: Here is an example of the exception

    ERROR:ui:Traceback (most recent call last):
      File "/home/chloe/testDir/alot/alot/ui.py", line 710, in apply_command
        cmd.apply(self)
      File "/home/chloe/testDir/alot/alot/commands/thread.py", line 585, in apply
        mt.expand(mt.root)
      File "/home/chloe/testDir/alot/alot/widgets/thread.py", line 217, in expand
        self.reassemble()
      File "/home/chloe/testDir/alot/alot/widgets/thread.py", line 192, in reassemble
        self._maintree._treelist = self._assemble_structure()
      File "/home/chloe/testDir/alot/alot/widgets/thread.py", line 234, in _assemble_structure
        bodytree = self._get_body()
      File "/home/chloe/testDir/alot/alot/widgets/thread.py", line 272, in _get_body
        self._bodytree = TextlinesList(bodytxt, att, att_focus)
      File "/home/chloe/testDir/alot/alot/widgets/thread.py", line 99, in __init__
        if settings.get_theming_attribute('global', 'tag2222'):
      File "/home/chloe/testDir/alot/alot/settings/manager.py", line 300, in get_theming_attribute
        return self._theme.get_attribute(colours, mode, name, part)
      File "/home/chloe/testDir/alot/alot/settings/theme.py", line 57, in get_attribute
        thmble = self._config[mode][name]
      File "/usr/lib/python3.7/site-packages/configobj.py", line 554, in __getitem__
        val = dict.__getitem__(self, key)

**Comment by Nelyah** [comment]
Ok, sorry about that. This was all me not knowing how things worked well enough.

If the theme value is specified in `alot/defaults/theme.spec` the error disappears (as there is a default value definied there)
