### ISSUE TITLE
TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by teto** [pazz/alot#1463]
Using current master:
Trying to run `alot --debug-level debug --logfile=./log --config config.test` with config.test
```
[tags]
[[unread]]
# focus=
normal=
```
gives
```
Traceback (most recent call last):
  File "/nix/store/dg88v36l9l6srlq1kq2zgvchn8jw5nwg-alot-dev/bin/.alot-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/dg88v36l9l6srlq1kq2zgvchn8jw5nwg-alot-dev/lib/python3.7/site-packages/alot/__main__.py", line 111, in main
    settings.read_config(cpath)
  File "/nix/store/dg88v36l9l6srlq1kq2zgvchn8jw5nwg-alot-dev/lib/python3.7/site-packages/alot/settings/manager.py", line 76, in read_config
    'gpg_key_hint': checks.gpg_key})
  File "/nix/store/dg88v36l9l6srlq1kq2zgvchn8jw5nwg-alot-dev/lib/python3.7/site-packages/alot/settings/utils.py", line 52, in read_config
    results = config.validate(validator, preserve_errors=True)
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/configobj.py", line 2310, in validate
    check = self.validate(validator, preserve_errors=preserve_errors, copy=copy, section=section[entry])
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/configobj.py", line 2310, in validate
    check = self.validate(validator, preserve_errors=preserve_errors, copy=copy, section=section[entry])
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/configobj.py", line 2266, in validate
    missing, ret_true, ret_false)
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/configobj.py", line 2205, in validate_entry
    missing=missing
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/validate.py", line 625, in check
    return self._check_value(value, fun_name, fun_args, fun_kwargs)
  File "/nix/store/ikyha1wsirl0fmm7dglpr4mlzki4b8jv-python3.7-configobj-5.0.6/lib/python3.7/site-packages/validate.py", line 657, in _check_value
    return fun(value, *fun_args, **fun_kwargs)
  File "/nix/store/dg88v36l9l6srlq1kq2zgvchn8jw5nwg-alot-dev/lib/python3.7/site-packages/alot/utils/configobj.py", line 35, in attr_triple
    attrstrings = (value + (6 - len(value)) * [None])[:6]
TypeError: can only concatenate tuple (not "list") to tuple
```

Looking at the doc https://alot.readthedocs.io/en/latest/configuration/theming.html#config-theming-attributes, clearly my config is wrong but the error message could be improved.

**Comment by pazz** [comment]
yes, agreed. thanks for reporting this.
