### ISSUE TITLE
cannot import twisted.internet.asyncioreactor

### ISSUE THREAD

**Issue by pazz** [pazz/alot#1549]
I got this after an `apt get update` on debian testing today...

```
[~] alot
Traceback (most recent call last):
  File "/home/pazz/.local/bin/alot", line 33, in <module>
    sys.exit(load_entry_point('alot', 'console_scripts', 'alot')())
  File "/home/pazz/.local/bin/alot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pazz/projects/alot/alot/__main__.py", line 19, in <module>
    from twisted.internet import asyncioreactor
  File "/usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py", line 16, in <module>
    from twisted.internet.base import DelayedCall
  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 27, in <module>
    from twisted.internet._resolver import (
  File "/usr/lib/python3/dist-packages/twisted/internet/_resolver.py", line 25, in <module>
    from twisted.internet.address import IPv4Address, IPv6Address
  File "/usr/lib/python3/dist-packages/twisted/internet/address.py", line 101, in <module>
    @attr.s(hash=False, repr=False, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
```

**Comment by pazz** [comment]
Fixed by `pip3 install --upgrade twisted --force-reinstall`...
