### ISSUE TITLE
Empty namedqueries gives divide by zero exception

### ISSUE THREAD

**Issue by aplund** [pazz/alot#1573]
Before you submit a bug report, please make sure that the issue still exists on the master branch!

**Describe the bug**

Calling namedqueries with zero defined queries gives divide by zero error

**Software Versions**
- Python version: 3.9.3
- Notmuch version: 0.31.4
- Alot version: git 1ade6de2

**To Reproduce**
Steps to reproduce the behaviour:
1. have no named queries defined in notmuch
2. call namedqueries in alot

**Error Log**

ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/alot/ui.py", line 723, in apply_command
    cmd.apply(self)
  File "/usr/lib/python3.9/site-packages/alot/commands/globals.py", line 591, in apply
    ui.buffer_open(buffers.NamedQueriesBuffer(ui, self.filtfun))
  File "/usr/lib/python3.9/site-packages/alot/buffers/namedqueries.py", line 21, in __init__
    self.rebuild()
  File "/usr/lib/python3.9/site-packages/alot/buffers/namedqueries.py", line 55, in rebuild
    self.querylist.set_focus(focusposition % len(self.queries))
ZeroDivisionError: integer division or modulo by zero

**Comment by randre03** [comment]
I receive the exact same error. 

I installed alot and notmuch via pacman on arch linux and am running the same python and notmuch versions as @aplund. I *think* I have defined a query in `.notmuch-config`. I have it as follows:

`[query]
all_mail=*`

(I am not certain this is the correct way, so perhaps the lack of any proper named queries in the db is contributing to the error?).
