### ISSUE TITLE
configurable unfold-query string for search.OpenThreadCommand

### ISSUE THREAD

**Issue by pazz** [pazz/alot#559]
when selection a threadline in search buffer, the created OpenThreadCommand
should receive the unfold querystring via parameter.
this would make it possible to unfold e.g. all matching mails that are also unread..

**Comment by lucc** [comment]
I tried to achieve a custom unfolding of messages with a `buffer_post_open` hook. I want to unfold all unread messages *and* the last (presumably newest) message in a thread. Currently I have this:
```python
def post_buffer_open(ui, dbm, buf):
    if isinstance(buf, alot.buffers.ThreadBuffer):
        count = buf.get_info()['message_count']
        if count > 1:
            buf.collapse_all()
            # this should move to the last message
            for i in range(count):
                buf.focus_next()
            # try to unfold the last message
            buf.expand(buf.get_selected_message_position())
            buf.unfold_matching('tag:unread', focus_first=True)
```
But I get an error message that `'NoneType' object has no attribute 'expand'`. But why is `buf` a NoneType when I checked it is instance of alot.buffers.ThreadBuffer? Any ideas what's going on or how I can fix it/achieve the desired result?

The log
```
DEBUG:manager:/home/luc/.config/alot/themes
DEBUG:manager:abook defined: {u'type': u'abook', u'abook_contacts_file': u'~/.config/abook/addressbook', 'ignorecase': True, 'command': None, 'regexp': None}
DEBUG:manager:abook defined: {'type': None, 'ignorecase': True, 'command': None, 'regexp': None, 'abook_contacts_file': '~/.abook/addressbook'}
INFO:ui:setup gui in 256 colours
DEBUG:ui:fire first command
DEBUG:ui:global command string: "search tag:inbox AND NOT tag:killed"
DEBUG:__init__:mode:global got commandline "search tag:inbox AND NOT tag:killed"
DEBUG:__init__:ARGS: [u'search', u'tag:inbox', u'AND', u'NOT', u'tag:killed']
DEBUG:__init__:cmd parms {'sort': None, 'query': [u'tag:inbox', u'AND', u'NOT', u'tag:killed']}
DEBUG:manager:Worker process 32416 spawned
DEBUG:manager:Worker process 32416 exited successfully
DEBUG:walker:EMPTY PIPE
DEBUG:ui:Got key (['down'], [27, 91, 66])
DEBUG:ui:cmdline: 'move down'
DEBUG:ui:search command string: "move down"
DEBUG:__init__:mode:search got commandline "move down"
DEBUG:__init__:ARGS: [u'move', u'down']
DEBUG:__init__:cmd parms {'movement': [u'down']}
DEBUG:search:down
DEBUG:ui:Got key (['enter'], [10])
DEBUG:ui:cmdline: 'select'
DEBUG:ui:search command string: "select"
DEBUG:__init__:mode:search got commandline "select"
DEBUG:__init__:ARGS: [u'select']
DEBUG:__init__:cmd parms {}
INFO:search:open thread view for thread:0000000000001d63: Grillchill Weihnachtsfeier
DEBUG:utils:command: elinks -dump /tmp/8TVesw.html
DEBUG:utils:parms: ('text/html=', 'charset=iso-8859-1')
DEBUG:utils:command: elinks -dump /tmp/p8D292.html
DEBUG:utils:parms: ('text/html=', 'charset=UTF-8')
DEBUG:utils:command: elinks -dump /tmp/IqVoJJ.html
DEBUG:utils:parms: ('text/html=', 'charset=UTF-8')
DEBUG:utils:command: elinks -dump /tmp/RrMYvT.html
DEBUG:utils:parms: ('text/html=', 'charset=utf-8')
DEBUG:buffers:Tbuffer: auto remove unread tag from msg?
DEBUG:buffers:Tbuffer: No, cursor on summary
DEBUG:buffers:setting focus to (u'DUB131-W10890D997F33E73B856599AD3E0@phx.gbl', (0,)) 
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 638, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/commands/search.py", line 39, in apply
    ui.buffer_open(sb)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 341, in buffer_open
    posthook(ui=self, dbm=self.dbman, buf=buf)
  File "/home/luc/.config/alot/hooks.py", line 186, in post_buffer_open
    buf.expand(buf.get_selected_message_position())
  File "/usr/lib/python2.7/site-packages/alot/buffers.py", line 571, in expand
    MT.expand(MT.root)
exceptions.AttributeError: 'NoneType' object has no attribute 'expand'

DEBUG:buffers:Tbuffer: auto remove unread tag from msg?
DEBUG:buffers:Tbuffer: No, cursor on summary
DEBUG:ui:Got key (['q'], [113])
DEBUG:ui:cmdline: 'bclose'
DEBUG:ui:thread command string: "bclose"
DEBUG:__init__:mode:thread got commandline "bclose"
DEBUG:__init__:ARGS: [u'bclose']
DEBUG:__init__:cmd parms {'redraw': None, 'force': False}
INFO:ui:closing current buffer [thread] Grillchill Weihnachtsfeier (4 messages)
DEBUG:ui:Got key (['q'], [113])
DEBUG:ui:cmdline: 'bclose'
DEBUG:ui:search command string: "bclose"
DEBUG:__init__:mode:search got commandline "bclose"
DEBUG:__init__:ARGS: [u'bclose']
DEBUG:__init__:cmd parms {'redraw': None, 'force': False}
INFO:globals:closing the last buffer, exiting
```

**Comment by pazz** [comment]
First off, the exception comes not from `buf` being `None` but from `buf._tree[sth]` being `None` (check the mentioned line).
However, there is a much easier way to focus the last msg, namely to use `buf.focus_last()`.
I think you can get what you want even without hooks:
use `select; fold *; move last ; unfold`..

I noticed while looking at the code that the help for the move command does not list all its possible targets. This should be fixed..

**Comment by lucc** [comment]
The key binding does the job nicely.
```
[bindings]
[[search]]
enter = select; fold *; unfold tag:unread; move last; unfold
```
