### ISSUE TITLE
UnicodeDecodeError: 'utf8'

### ISSUE THREAD

**Issue by tilllt** [pazz/alot#674]
Traceback (most recent call last):
  File "/home/till/.local/bin/alot", line 20, in <module>
    main()
  File "/home/till/.local/lib/python2.7/site-packages/alot/init.py", line 157, in main
    settings.read_notmuch_config(notmuchconfig)
  File "/home/till/.local/lib/python2.7/site-packages/alot/settings/manager.py", line 55, in read_notmuch_config
    self._notmuchconfig = read_config(path, spec)
  File "/home/till/.local/lib/python2.7/site-packages/alot/settings/utils.py", line 26, in read_config
    file_error=True, encoding='UTF8')
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1230, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1290, in _load
    infile = self._handle_bom(infile)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1431, in _handle_bom
    return self._decode(infile, self.encoding)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1491, in _decode
    return infile.decode(encoding).splitlines(True)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 1250: invalid continuation byte

how can i solve this?

**Comment by dcbaker** [comment]
This is a really old bug with no further reply, and It really looks like an error created by a file encoded with a non-utf8 encoding causing trouble.

Feel free to reopen if it's not.
