### ISSUE TITLE
Replying to some mails fails with decoding error

### ISSUE THREAD

**Issue by telmich** [pazz/alot#725]
Trying to reply to a specifc mail I get this error:

'ascii' codec can't encode character u'\xfc' in position 17: ordinal not in range(128)
(check the log for details)

I wonder if decoding to ascii is probably the wrong approach for a terminal having LANG=en_US.UTF-8?

**Comment by varac** [comment]
I get the same, using todays master and python 3:

```
DEBUG:__init__:ARGS: ['reply', '--all']
DEBUG:__init__:cmd parms {'all': True, 'listreply': None, 'spawn': None}
DEBUG:envelope:TEMPLATE: None
DEBUG:utils:unquoted header: |Re: ...|
DEBUG:thread:candidate addresses: [('a', 'a@b.c')]
DEBUG:thread:candidate addresses: [('', 'öwe <oewe@b.c>')]
DEBUG:thread:match!: 'varac@d.e'
DEBUG:thread:using realname: "varac"
DEBUG:thread:using address: varac@d.e
DEBUG:thread:Replying to own message, set recipients to: ['a', 'a@b.c']
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/ui.py", line 709, in apply_command
    await cmd.apply(self)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/thread.py", line 236, in apply
    my_addresses, mail.get_all('Cc', []))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.7-py3.6.egg/alot/commands/thread.py", line 309, in clear_my_address
    new_value.append(formataddr((name, str(address))))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 1: ordinal not in range(128)
```

Alot stumbles on the Cc address, which shows up quoted in the thread buffer:

```
    From         varac <varac@d.e>
    To             a <a@b.c>
    Cc            "öwe <oewe@b.c>"
    ...
```

**Comment by varac** [comment]
This is possible a duplicate of #1300

**Comment by dcbaker** [comment]
I can't reproduce the encode error, what I can reproduce is that the CC will show up as a quoted printable string, `=?utf-8?q?=C3=96we?= <oewe@example.com>`, which is obviously not ideal. That problem is due to the fact that we really need an abstraction between the raw email headers and what we display.

**Comment by dcbaker** [comment]
wait, it's the address with the non-ascii in it? ohhhh, yeah, the python builtin definitely doesn't handle that.

**Comment by stevenengler** [comment]
Not sure how much it's related since I'm not familiar with how Python handles encodings, but I had the same error when starting alot (and therefore the search buffer) since some of my email subjects had a "•" in them. They would crash with:

    ERROR:ui:Traceback (most recent call last):
      File "/root/alot/alot/ui.py", line 711, in apply_command
        cmd.apply(self)
      File "/root/alot/alot/commands/globals.py", line 126, in apply
        sort_order=self.order))
      File "/root/alot/alot/ui.py", line 405, in buffer_open
        self.buffer_focus(buf)
      File "/root/alot/alot/ui.py", line 465, in buffer_focus
        self.update()
      File "/root/alot/alot/ui.py", line 656, in update
        self.mainloop.draw_screen()
      File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 587, in draw_screen
        self.screen.draw_screen(self.screen_size, canvas)
      File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 850, in draw_screen
        self.write(l)
      File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 279, in write
        self._term_output_file.write(data)
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 27: ordinal not in range(128)

The fix for me was to use:

    $ export PYTHONIOENCODING=utf8

**Comment by varac** [comment]
> export PYTHONIOENCODING=utf8 indeed fixed at least my issue I posted earlier (#725 (comment)).

Oh noes, I was wrong - it did not fix it :/

**Comment by varac** [comment]
I could reproduce the `UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 2: ordinal not in range(128)` error by sending this mail to myself, and them trying to group-reply to it:

```
From: Värac <varac@….net>
To: Värac <varac@….net>
Cc: "Värac <varac@….net>"
Subject: Eat some unicode äöüß™å !
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit

Liebe Grüße!
```

**Comment by lucc** [comment]
In order to find out if the utf8 chars in the subject are relevant for your error message please look at the stack trace and see where it fails when doing what. 

Is it even allowed by the standard that header fields have unencoded non ascii chars? From the name of the header field `Content-Type` and `Content-Transfer-Encoding` I assume that they are only valid for the body. And any parser would be in a catch 22 if they had to parse the header fields in order to find out how to parse the header fields.

**Comment by varac** [comment]
@lucc I could reproduce the error with this mail:

```
From: Varac <varac@….net>
To: Varac <varac@….net>
Cc: "Värac <varac@….net>"
Subject: Hello
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit

Hi!
```

This is from the log:

```
DEBUG:ui:Got key (['r'], [114])
DEBUG:ui:cmdline: 'reply --all'
DEBUG:ui:thread command string: "reply --all"
DEBUG:__init__:mode:thread got commandline "reply --all"
DEBUG:__init__:ARGS: ['reply', '--all']
DEBUG:__init__:cmd parms {'all': True, 'listreply': None, 'spawn': None}
DEBUG:utils:Content-Transfer-Encoding: "8bit"
DEBUG:utils:assuming Content-Transfer-Encoding: 8bit
DEBUG:envelope:TEMPLATE: None
DEBUG:utils:unquoted header: |Hello|
DEBUG:thread:candidate addresses: [('Varac', 'varac@….net')]
DEBUG:thread:using realname: "Varac"
DEBUG:thread:using address: varac@varac.net
DEBUG:thread:Replying to own message, set recipients to: ['Varac <varac@….net>']
ERROR:ui:Traceback (most recent call last):
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.8-py3.6.egg/alot/ui.py", line 709, in apply_command
    await cmd.apply(self)
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.8-py3.6.egg/alot/commands/thread.py", line 223, in apply
    account, mail.get_all('Cc', []))
  File "/home/varac/.local/lib/python3.6/site-packages/alot-0.8-py3.6.egg/alot/commands/thread.py", line 296, in clear_my_address
    new_value.append(formataddr((name, str(address))))
  File "/usr/lib/python3.6/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 2: ordinal not in range(128)
```

**Comment by varac** [comment]
Once I replace `Cc: "Värac <varac@….net>"` with `Cc: "Varac <varac@….net>"` the error is gone.

**Comment by lucc** [comment]
Which might be what we expect given that [RFC2047](https://tools.ietf.org/html/rfc2047) does not seem to allow unencoded 8-bit characters in header fields.

**Comment by jonassmedegaard** [comment]
This issue happens for me with emails written by myself in alot which I then try reply to.  The header fields _look_ like they contain 8bit characters when displayed in alot, but the raw email in Maildir has headers like these:
```
To: =?utf-8?q?Bernhard_=C3=9Cbelacker_=3Cbernhardu=40mailbox=2Eorg=3E?=
Cc: =?utf-8?q?Alexander_Reichle-Schmehl_=3Calexander=40alphamar=2Eorg=3E=2C_942055=40bugs=2Edebian=2Eorg=2C_Michael_Sch=C3=BCtz_=3Cder=2Eschultze=40directbox=2Ecom=3E?=
```
So I suspect this cannot be waved off as non-compliant headers.
