### ISSUE TITLE
runtime error on archlinux

### ISSUE THREAD

**Issue by tgirod** [pazz/alot#765]
After a fresh install of ```alot-git``` on archlinux, I get the following error when running alot:

```
Traceback (most recent call last):
  File "/usr/bin/alot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3057, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 639, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 940, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 827, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-magic' distribution was not found and is required by alot
```

python-magic is installed on my system, but the package is called ```python2-magic``` (```python-magic``` is the python3 version). Could it be the cause ?

**Comment by pazz** [comment]
yes, this seems to be a packaging issue with arch linux, also discussed 
here: https://aur.archlinux.org/packages/alot/
I'll close this issue here as there is not much (pun intended) I can do about python packaging in arch.
Cheers,
/p

**Comment by MacGyverNL** [comment]
I am unable to find this discussion and encountering the problem on the testing branch, any pointers to what exactly this packaging problem was?
