### ISSUE TITLE
list index out of range when refreshing

### ISSUE THREAD

**Issue by josch** [pazz/alot#781]
Hi, when I refresh my search for `tag:unread` I get the following traceback:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/share/alot/alot/ui.py", line 638, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/share/alot/alot/commands/globals.py", line 141, in apply
    ui.update()
  File "/usr/share/alot/alot/ui.py", line 580, in update
    self.mainloop.draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 565, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1079, in render
    focus and self.focus_part == 'body')
  File "/usr/share/alot/alot/buffers.py", line 37, in render
    return self.body.render(size, focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 339, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 704, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 674, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 402, in calculate_visible
    next, pos = self.body.get_next( pos )
  File "/usr/share/alot/alot/walker.py", line 32, in get_next
    return self._get_at_pos(start_from + self.direction)
  File "/usr/share/alot/alot/walker.py", line 58, in _get_at_pos
    widget = self._get_next_item()
  File "/usr/share/alot/alot/walker.py", line 71, in _get_next_item
    next_widget = self.containerclass(next_obj, **self.kwargs)
  File "/usr/share/alot/alot/widgets/search.py", line 27, in __init__
    self.rebuild()
  File "/usr/share/alot/alot/widgets/search.py", line 148, in rebuild
    minw, maxw, align_mode)
  File "/usr/share/alot/alot/widgets/search.py", line 106, in _build_part
    lastcontent = ' '.join([m.get_text_content() for m in msgs])
  File "/usr/share/alot/alot/db/message.py", line 250, in get_text_content
    return extract_body(self.get_email(), types=['text/plain'])
  File "/usr/share/alot/alot/db/message.py", line 73, in get_email
    self._email = message_from_file(f_mail)
  File "/usr/share/alot/alot/db/utils.py", line 110, in message_from_file
    ct = m.get_payload(1).get_content_type()
  File "/usr/lib/python2.7/email/message.py", line 193, in get_payload
    payload = self._payload[i]
exceptions.IndexError: list index out of range
```

**Comment by meskio** [comment]
I get the same traceback, not refreshing a search but opening a thread. I can confirm it happens running the latest alot from the master branch.

This happens with a multipart/signed email where the signed part is missing (a malformed email). I think it's easy to fix, just checking that the part exist before trying to fetch it. I'll give it a try.

**Comment by pazz** [comment]
Thanks! @josh: can you confirm this?

**Comment by josch** [comment]
nope, I cannot reproduce the problem anymore and was hoping that the traceback would suffice. Thus I can neither confirm nor deny that a malformed multipart/signed email was the cause for me.

**Comment by pazz** [comment]
OK, thanks anyway. In any case, this looks like a pretty safe patch to me.

Quoting josch (2016-03-24 12:06:50)
