### ISSUE TITLE
assertion error with certain searches

### ISSUE THREAD

**Issue by josch** [pazz/alot#782]
Hi,

when doing a certain search with alot 0.3.6, I get the following assertion error:

    Traceback (most recent call last):
      File "/usr/bin/alot", line 20, in <module>
        main()
      File "/usr/share/alot/alot/init.py", line 186, in main
        UI(dbman, cmdstring)
      File "/usr/share/alot/alot/ui.py", line 87, in __init__
        self.mainloop.run()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
        self.screen.run_wrapper(self._run)
      File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
        return fn()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 314, in _run
        self.draw_screen()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 565, in draw_screen
        canvas = self._topmost_widget.render(self.screen_size, focus=True)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
        canv = self._original_widget.render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1079, in render
        focus and self.focus_part == 'body')
      File "/usr/share/alot/alot/buffers.py", line 37, in render
        return self.body.render(size, focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 487, in render
        canvas = widget.render((maxcol,))
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/share/alot/alot/widgets/search.py", line 168, in render
        return urwid.AttrMap.render(self, size, focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
        canv = self._original_widget.render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2081, in render
        focus = focus and self.focus_position == i)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
        canv = self._original_widget.render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1008, in render
        return apply_text_layout(text, attr, trans, maxcol)
      File "/usr/lib/python2.7/dist-packages/urwid/canvas.py", line 1288, in apply_text_layout
        s = LayoutSegment(seg)
      File "/usr/lib/python2.7/dist-packages/urwid/text_layout.py", line 267, in __init__
        assert self.sc > 0, repr(seg)
    AssertionError: (0, 0, 0)

This search is my `initial_command` so I do it rather often. Since the problem only started occuring today, I added a `and not date:today..today` to my query, suspecting that the new email I got today was responsible. But it was not and alot was properly able to show it (the mail of yesterday shows fine as well). So I am guessing that this is something about the combination of mail currently in my inbox?

**Comment by pazz** [comment]
Hi!

I'm not sure but it could be down to urwid trying to render a text field of size 0.
So is it possible that this message carries a tag that you display as a symbol
your terminal cannot handle? or do you display some header whose value has zero length?
Thanks for reporting/debugging this :)

**Comment by josch** [comment]
Good news, I found the offending message that creates this assertion error and I also found the additional trigger that I missed before. It turns out, the assertion is only triggered if my terminal has a certain width but not otherwise.

You can find the message that creates the assertion error if my terminal has a certain width here: https://mister-muffin.de/p/VDC8

Thanks for still maintaining alot!

**Comment by josch** [comment]
Forgot to add some additional info:

 - the message is obviously spam
 - its md5sum is: bfbd59cae8dab6b8f64855b1c514b600

**Comment by three-comrades** [comment]
For what it's worth, I can reproduce this  with my tiled window manager (i3), but only if the the terminal is rather narrow. This is a screenshot of the configuration that causes the crash with my 1366x768 screen: [click](https://github.com/three-comrades/alot/blob/screenshot/2018-02-16-111335_1366x768_escrotum.png)


To reproduce:
- add the email to your notmuch index
- open two terminals side by side.
- in the right one, open a named screen session: `screen -S alot`
- resize the terminals such that the right one is very small
- move your mouse cursor all the way to the left side of the screen, so that the left window is always the active one.
- run a script like this and ctrl-c out of it, when the error occurs:
```
#! /bin/sh

while true
do
    i3-msg resize shrink width 1 px or 1 ppt
    sleep 0.5
    screen -S alot -p 0 -X stuff "alot -l log -d debug search to:mister-muffin.de^M"
    sleep 0.5
    screen -S alot -p 0 -X stuff "q"
done
```

**Comment by pazz** [comment]
hm.. I cannot reproduce this :/
I see the mail, with lots of asean unicode symbols everywhere. Resizing (also in a floating i3 window here) works as expected down to a terminal size of 1 char. I can size-up again, an all is well. no error.
I'm on the master branch and `Python 2.7.14+`
