### ISSUE TITLE
Reply to own mail

### ISSUE THREAD

**Issue by DonHansDampf** [pazz/alot#784]
When i try to reply to my own mail, i get an error. Nothing special. But confused me for like 2 days. The --debug-level=error log is:

```
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/alot-0.3.6-py2.7.egg/alot/ui.py", line 638, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/alot-0.3.6-py2.7.egg/alot/commands/thread.py", line 211, in apply
    to = ', '.join(recipients)
exceptions.TypeError: sequence item 0: expected string, NoneType found
```

Hope this helps!

Greetings

**Comment by pazz** [comment]
does 98f1ba4 fix this for you?

**Comment by dcbaker** [comment]
I can't replicate this on master.
