### ISSUE TITLE
signature not appended

### ISSUE THREAD

**Issue by tinkyholloway** [pazz/alot#826]
A signature with a first non-white space character of `(` results in the signature not being used.

To replicate, create a signature file as:
```
(foobar
```
The above file is not included in an email composition. The below file works as intended:
```
--
(foobar
```

**Comment by pazz** [comment]
```
DEBUG:globals:has signature
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.7-py2.7.egg/alot/commands/globals.py", line 791, in apply
    'no')) == 'no':
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.3.7-py2.7.egg/alot/ui.py", line 461, in choice
    assert select in choices.values() + [None]
exceptions.AttributeError: 'str' object has no attribute 'values'

```
