### ISSUE TITLE
bullet proof alot

### ISSUE THREAD

**Issue by teythoon** [pazz/alot#83]
alot just crashed, this should be avoided and exceptions caught and turned into notifications at the right place (TM).

```
Traceback (most recent call last):
  File "bin/alot", line 20, in <module>
    main()
  File "/tmp/alot/alot/init.py", line 114, in main
    args.colours,
  File "/tmp/alot/alot/ui.py", line 79, in __init__
    self.mainloop.run()
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/raw_display.py", line 229, in run_wrapper
    return fn()
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/main_loop.py", line 307, in _run
    self.event_loop.run()
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/main_loop.py", line 1159, in wrapper
    rval = f(*args,**kargs)
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/main_loop.py", line 358, in _update
    self.process_input(keys)
  File "/home/teythoon/.local/lib/python2.6/site-packages/urwid-1.0.0-py2.6-linux-x86_64.egg/urwid/main_loop.py", line 447, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/tmp/alot/alot/ui.py", line 42, in keypress
    self.ui.apply_command(cmd)
  File "/tmp/alot/alot/ui.py", line 397, in apply_command
    cmd.apply(self)
  File "/tmp/alot/alot/command.py", line 852, in apply
    ui.apply_command(FoldMessagesCommand())
  File "/tmp/alot/alot/ui.py", line 397, in apply_command
    cmd.apply(self)
  File "/tmp/alot/alot/command.py", line 691, in apply
    widget.fold(visible=True)
  File "/tmp/alot/alot/widgets.py", line 377, in fold
    hw = self._get_header_widget()
  File "/tmp/alot/alot/widgets.py", line 324, in _get_header_widget
    cols = [MessageHeaderWidget(self.message.get_email(), displayed)]
  File "/tmp/alot/alot/message.py", line 72, in get_email
    f_mail = open(self.get_filename())
IOError: [Errno 2] No such file or directory: '/home/teythoon/Maildir/.lists.mafia/cur/1317405769.M300650P17429.thinkbox,S=4783,W=4877:2,'
```

**Comment by pazz** [comment]
on it ;) 
I'm closing this issue as too vague.
