### ISSUE TITLE
AttributeError when opening a thread.

### ISSUE THREAD

**Issue by josch** [pazz/alot#842]
Hi,

I get the following error when I try to open a specific thread:

```
Traceback (most recent call last):
  File "/usr/bin/alot", line 20, in <module>
    main()
  File "/usr/share/alot/alot/init.py", line 186, in main
    UI(dbman, cmdstring)
  File "/usr/share/alot/alot/ui.py", line 87, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1183, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1142, in _twisted_idle_callback
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 551, in entering_idle
    self.draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 565, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1079, in render
    focus and self.focus_part == 'body')
  File "/usr/share/alot/alot/buffers.py", line 406, in render
    return self.body.render(size, focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 402, in calculate_visible
    next, pos = self.body.get_next( pos )
  File "/usr/share/alot/alot/foreign/urwidtrees/widgets.py", line 80, in get_next
    return self._get(self._tree.next_position(pos))
  File "/usr/share/alot/alot/foreign/urwidtrees/widgets.py", line 67, in _get
    res = self[pos], pos
  File "/usr/share/alot/alot/foreign/urwidtrees/lru_cache.py", line 102, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/share/alot/alot/foreign/urwidtrees/widgets.py", line 53, in __getitem__
    entry = self._tree.get_decorated(pos)
  File "/usr/share/alot/alot/foreign/urwidtrees/nested.py", line 86, in get_decorated
    return self._get_decorated_entry(self._tree, pos)
  File "/usr/share/alot/alot/foreign/urwidtrees/nested.py", line 82, in _get_decorated_entry
    entry = tree.decorate(pos[0], entry, is_first=isf)
  File "/usr/share/alot/alot/foreign/urwidtrees/decoration.py", line 475, in decorate
    line = urwid.Columns(cols, box_columns=range(len(cols))[:-1])
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1761, in __init__
    if focus_column is None and w.selectable():
AttributeError: 'NoneType' object has no attribute 'selectable'
```

The thread in question seems to be some spam email so chances are that this email is malformed in some way in the hopes to trigger some bugs in certain MUAs. Just in case, let me paste this email here. Maybe it even helps you to reproduce the bug on your system:

```
Return-Path: <admin@cluster1.durangeportal.com>
Received: from mailly.debian.org ([82.195.75.114]) by mx-ha.web.de (mxweb005)
 with ESMTPS (Nemesis) id 0LwsPI-1ZvAve1Amu-016NrI for <j.schauer@email.de>;
 Fri, 19 Feb 2016 05:01:34 +0100
Received: from h15.cluster1.durangeportal.com ([82.211.27.15])
	by mailly.debian.org with esmtp (Exim 4.84)
	(envelope-from <admin@cluster1.durangeportal.com>)
	id 1aWcG6-0001of-0R
	for j.schauer@email.de; Fri, 19 Feb 2016 04:01:34 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=dkim; d=cluster1.durangeportal.com;
 h=Sender:From:Subject:To:Content-Type:MIME-Version:Reply-To:Date; i=useragent@cluster1.durangeportal.com;
 bh=/52R3eX8aX+W5mSJeTi8AGXf9Wc=;
 b=BbrBfmy28WI0HZMSWh49tyzCV+oc1aNOihWPQtdeDZa21M4LVWmWwelJJYxOyKFVr27ANqZ8deJd
   Mntjn39AQTAorI3Fqo0BFEOtmY1Tx/AKsPDaq+eCqtmO0KHPb9GOzzghdznDSYzkMeVwCPoH4Mwa
   2b6hdFukzI8kruWdUak=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=dkim; d=cluster1.durangeportal.com;
 b=QseDDFRzX1tUakGyJvfd7NnCJoMftpdq/9sjR9moehMEc1SdFXPqoYARyMQbxDPYLaBqSFDiG7XL
   FUPH5LvydCzt6Iw3KjkUNf3xcAkkzUa5HlAKOjXmC3GJXOra1q5v5AiseQTCWCtrYvo6u0LL/Z+z
   7u03cBM4YLAYwYOYu0Y=;
Sender :useragent@cluster1.durangeportal.com
From: "Moataz Hegab" <admin@cluster1.durangeportal.com>
Subject: Thursday, 18 February 2016
To: josch@debian.org
Content-Type: multipart/alternative; boundary="gU3pQY9bt1PShstaJwFB8UqIy3WAsR=_kR0"
MIME-Version: 1.0
Reply-To: moatazhegab@aol.com
Date: Thu, 18 Feb 2016 21:49:58 -0500
Envelope-To: <j.schauer@email.de>
X-UI-Filterresults: unknown:5;V01:K0:1OO5MssBTT4=:+/OCMwArJ1gomIPIXpACIe7hVG
 /ZQn0S6aVUpkt4dq/aWM/rkeRP81m46dL+MEbfha5g6ZV3vM3uJ/GJKudQVaAVlPa/5W9GreB
 SdwZqffKAc5BhJ9y6hTuOVoZB0kmY88UVvZBzwmdme6MXpWYv4r56TPsEkWHKWsjTw4htCFJJ
 JeULZa7EE6jqnTEzRHGalW0bLgfSD/lWUgHjgyAdm4PLKvejgngQkcWW17f4ArGculvtnXmEU
 mKw9pRbLXazljcbVDyNWioTs6YS7j/Qn1825Yp+EtObhJS5GVcRY5UlEVqf0YqJUWwmyrBzRv
 GnPfIm8lYbayYfsuZgixm4BR4ehl+zyvgMPP/4qK5xZNPcKD44SYjvAOGKS/pePKiYNr6CBzD
 pyScxjtWEGHDV4CnemItqPCudK60yzC/W4I3AkH0fC/X5BJ5n8K0f5KKm1yQaLAh245IUa7kL
 /RNRu2lhwEdgbp++tTqBzQl8599yM5KlATTiWd5dP0soegvyyEwbEhNddFoX42ZPxuofZopHe
 Em9zpfVrnwrpA6gZ1oM2A3MnNYezwrGXKFOO1W510OgVOgc8d170G+BlkU1NfbnDve+y0RFyj
 m43K2Wi4XCFylarlJ4P+D+symsIEEfsQuPC1s2u7AwM4q3isGMzEWLYEAc2l6ynzhza1/ZXkK
 qI0uJ1ctcqlOqxodeCLl8GTTES4SCXyu3HVlADEAdxZhfUMJM9Kc+5w/IGeRvT7+dKvklG3XC
 DkQpK3HSCapY6KrnLAh5tRa+8WJtUnNCPUz3+OPv6TcrLLh6Z9x+BVdxByh46sf0wkrW7HP5Z
 vNPULRN7IkFJSc4oHte9G6uZkEQsy3slalfS0xZxL2ifiu5WZyVmkAUIg571Y88PpshjBH9bM
 SHNVZ005VNgPsfQhRcDFcNiJKcRDVt1JeQf2Ui+NqM+HDCVRZ04+ujERxDOA++L0LTH1ItqDM
 kYgb6tKlbJCXk23glwAUDEurpioOyuCEvEoMF/TmfF8y/4y5EiwraawX7/R9zQDL83hjBBR7E
 5UUgPJfvKx7QWr+uifgFUrwnXxTeITqUZ8gD3an553hix4K88kFnkHZhddJPUAWMmwgoJTo8E
 0iJBwxaQUDQwRwvKg8lD9mtXFiSEgYKP0MyuJrQsRkypELG6Te8JeLrFrl9j9Crh3lgllTT6V
 Hascmys02qSfNy/TCpc5r2pZOltYD/txRZIxCeK3o7FM79LZeAsyEEs+o1irsRGxQn2bRna/V
 RIcPsp4x7PU2Q14HH+Mb8BVnEMhkTDdXwjW4TDl952LAcDRT5Eg5W9ZbRvxsjCm3Kyc9/sik4
 GnyyET9OyU/77Ly6mjVumCahVjCn6u8m9qsFvhIEhJWCLJR6kbvXk58LJuaJ84glRldaP7pp9
 LN9A0Khts4cKmUcaR9p4zVBWz4ltmSkNeILDUT14prp0ZTWVKldndgKRS/Y+JH48wcGKlDR9N
 BeDRzIufggffYlOfrrtm4RkZXYfNwPuYIXnb6Fv1EK8wDG5mlCmKLWVoaCyP7pwn64WzebB8a
 X2SWzKgVR8JFLEeVmV6yrYDHQ28c/FfSs9DS1Gpbg9dZGJcwUnjungs63Y2gk39xL370aAvvu
 E1Sn8iw52iCecJkZLlYVl8QyQXLdi8mFvxII5IHosEC9DvWBps8I96Qwp2LUCpwFRnVj0Mt0/
 tw=

This is a multi-part message in MIME format

--gU3pQY9bt1PShstaJwFB8UqIy3WAsR=_kR0
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

 - This mail is in HTML. Some elements may be ommited in plain text. -

Sir,
I am writing from the "Kuwait Finance and Investment Company", a premi=
er financial and investment company here in Kuwait and the GCC Region.
I am a financial consultant to an investor from a Mineral-Oil Rich Afr=
ican Country with sensitive political background who wants to invest o=
utside his country and without the appearance of his name on the inves=
tments.
As stated above, my client had approached me with a mandate to seek fo=
r individuals with professional experience in financial management tha=
t can help him channel these funds into profitable investments outside=
 Africa where these funds could exist outside his name and country.
Should this be of interest to you, kindly respond with your CV and/or =
personal profile so we can discuss further.
Moataz Hegab
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D
Sir,
Ich schreibe aus der "Kuwait Finance und Investment Company", ein Prem=
ier Finanz- und Investment-Unternehmen hier in Kuwait und der GCC-Region.
Ich bin ein Finanzberater an einen Investor aus einem Mineral-=D6l rei=
chen afrikanischen Land mit sensiblen politischen Hintergrund, der au=
=DFerhalb seines Landes und ohne das Aussehen seines Namens auf der Ka=
pitalanlagen investieren will.
Wie bereits erw=E4hnt, hatte mein Klient n=E4herte sich mir mit einem =
Mandat, Kanal zu suchen f=FCr Personen mit Berufserfahrung in der Fina=
nzverwaltung, die ihm helfen kann diese Mittel in profitable Investiti=
onen au=DFerhalb Afrikas wo diese Mittel au=DFerhalb seines Namens und=
 Land existieren k=F6nnte.
Dies sollte sein, die Sie interessieren, bitte Antwort mit Ihren CV un=
d/oder pers=F6nliches Profil, so dass wir weiter diskutieren k=F6nnen.
Moataz Hegab

--gU3pQY9bt1PShstaJwFB8UqIy3WAsR=_kR0
Content-Type: text/html
Content-Transfer-Encoding: quoted-printable

<HTML><HEAD></HEAD>
<BODY><FONT color=3D#191919 size=3D5 face=3DSegoeUI><FONT color=3D#191=
919 size=3D5 face=3DSegoeUI><FONT color=3D#191919 size=3D5 face=3DSego=
eUI>
<P>Sir,</P>
<P>I am writing from the "Kuwait Finance and Investment Company", a pr=
emier financial and investment company here in Kuwait and the GCC Regi=
on.</P>
<P>I am a financial consultant to an investor from a Mineral-Oil Rich =
African Country with sensitive political background who wants to inves=
t outside his country and without the appearance of his name on the in=
vestments.</P>
<P>As stated above, my client had approached me with a mandate to seek=
 for individuals with professional experience in financial management =
that can help him channel these funds into profitable investments outs=
ide Africa where these funds could exist outside his name and country.=
</P>
<P>Should this be of interest to you, kindly respond with your CV and/=
or personal profile so we can discuss further.</P>
<P>Moataz Hegab</P>
<P>=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D</P>
<P>Sir,</P>
<P>Ich schreibe aus der "Kuwait Finance und Investment Company", ein P=
remier Finanz- und Investment-Unternehmen hier in Kuwait und der GCC-R=
egion.</P>
<P>Ich bin ein Finanzberater an einen Investor aus einem Mineral-=D6l =
reichen afrikanischen Land mit sensiblen politischen Hintergrund, der =
au=DFerhalb seines Landes und ohne das Aussehen seines Namens auf der =
Kapitalanlagen investieren will.</P>
<P>Wie bereits erw=E4hnt, hatte mein Klient n=E4herte sich mir mit ein=
em Mandat, Kanal zu suchen f=FCr Personen mit Berufserfahrung in der F=
inanzverwaltung, die ihm helfen kann diese Mittel in profitable Invest=
itionen au=DFerhalb Afrikas wo diese Mittel au=DFerhalb seines Namens =
und Land existieren k=F6nnte.</P>
<P>Dies sollte sein, die Sie interessieren, bitte Antwort mit Ihren CV=
 und/oder pers=F6nliches Profil, so dass wir weiter diskutieren k=F6nn=
en.</P>
<P>Moataz Hegab</P></FONT></FONT></FONT></BODY></HTML>

--gU3pQY9bt1PShstaJwFB8UqIy3WAsR=_kR0--
```

**Comment by pazz** [comment]
dup of #839

**Comment by pazz** [comment]
thx for the details. let's discuss it in the older thread.
