### ISSUE TITLE
append signature content (mimetype text) to the body fails

### ISSUE THREAD

**Issue by logol** [pazz/alot#848]
Hi, when I set these settings in the account section:

signature = path/to/signature
signature_as_attachment = False

alot fails when trying to compose a mail.
The signature file is just plain text (no html or vcf).

```
DEBUG:ui:Got key (['enter'], [10])
DEBUG:globals:has signature
DEBUG:globals:is file
ERROR:ui:Traceback (most recent call last):
  File "/home/.../.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/.../.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/home/.../.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/.../.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/home/.../.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/.../.local/lib/python2.7/site-packages/alot/commands/globals.py", line 782, in apply
    enc = helper.guess_encoding(sigcontent)
  File "/home/.../.local/lib/python2.7/site-packages/alot/helper.py", line 438, in guess_encoding
    raise Exception('Unknown magic API')
exceptions.Exception: Unknown magic API

DEBUG:ui:Got key (['q'], [113])
```

**Comment by dcbaker** [comment]
This is a pretty odd looking bug. it seems like there's something wrong with you `magic` package. Since this bug is over a year old I'm going to close it, but please reopen if you still have this problem and want to follow up.
