### ISSUE TITLE
'NoneType' error when trying to compose/reply to a mail

### ISSUE THREAD

**Issue by xiroV** [pazz/alot#872]
Hi

I'm not sure if this is a code issue or if I've misconfigured alot in some way, but here's the issue:

Each time I press "r" in a mail/thread-view to reply to it the following Python error appears accross the screen:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 633, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/alot/commands/envelope.py", line 391, in apply
    refocus=self.refocus)
  File "/usr/lib/python2.7/site-packages/alot/commands/globals.py", line 296, in __init__
    if '%s' in editor_cmdstring:
exceptions.TypeError: argument of type 'NoneType' is not iterable
```

The same error appears when I press "m" to compose a mail, after I've entered a "To:" and a "Subject:".

There seems to be no exception to when this happens.

My config file (cencored my email though):
```
[accounts]
    [[xirov]]
        realname = Brian Pedersen
        address = ***@***.com
        sendmail_command = msmtp --account=xirov -t
        sent_box = maildir:///home/xirov/.mail/xirov/Sent
        draft_box = maildir:///home/xirov/.mail/xirov/Drafts
```

So can anyone figure what I did wrong? If you want me to send further information, please specify how I get that information.

Thanks!

**Comment by TomasTomecek** [comment]
looks like that your editor command is `None`; putting this into your config should resolve the issue:

```
editor_cmd = /usr/bin/vim -f -c 'set filetype=mail'
```

**Comment by xiroV** [comment]
Thanks a lot! That worked!
