### ISSUE TITLE
Exception "list index out of range" in search view

### ISSUE THREAD

**Issue by josch** [pazz/alot#891]
Hi,

since recently (I suspect it's one of the emails alot tries to show) I get the following exception after a search:

    DEBUG:globals:CMDLINE: search tag:unread and not tag:spam
    DEBUG:ui:search command string: "search tag:unread and not tag:spam"
    DEBUG:__init__:mode:search got commandline "search tag:unread and not tag:spam"
    DEBUG:__init__:ARGS: [u'search', u'tag:unread', u'and', u'not', u'tag:spam']
    DEBUG:__init__:cmd parms {'sort': None, 'query': [u'tag:unread', u'and', u'not', u'tag:spam']}
    DEBUG:manager:Worker process 17694 spawned
    ERROR:ui:Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
        callbackKeywords=kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
        self._runCallbacks()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/share/alot/alot/ui.py", line 638, in call_apply
        return defer.maybeDeferred(cmd.apply, self)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
        result = f(*args, **kw)
      File "/usr/share/alot/alot/commands/globals.py", line 94, in apply
        sort_order=self.order))
      File "/usr/share/alot/alot/ui.py", line 336, in buffer_open
        self.buffer_focus(buf)
      File "/usr/share/alot/alot/ui.py", line 397, in buffer_focus
        self.update()
      File "/usr/share/alot/alot/ui.py", line 580, in update
        self.mainloop.draw_screen()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 578, in draw_screen
        canvas = self._topmost_widget.render(self.screen_size, focus=True)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
        canv = self._original_widget.render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1083, in render
        focus and self.focus_part == 'body')
      File "/usr/share/alot/alot/buffers.py", line 37, in render
        return self.body.render(size, focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 457, in render
        (maxcol, maxrow), focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 339, in calculate_visible
        self._set_focus_complete( (maxcol, maxrow), focus )
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 704, in _set_focus_complete
        (maxcol,maxrow), focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 674, in _set_focus_first_selectable
        (maxcol, maxrow), focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 402, in calculate_visible
        next, pos = self.body.get_next( pos )
      File "/usr/share/alot/alot/walker.py", line 32, in get_next
        return self._get_at_pos(start_from + self.direction)
      File "/usr/share/alot/alot/walker.py", line 58, in _get_at_pos
        widget = self._get_next_item()
      File "/usr/share/alot/alot/walker.py", line 71, in _get_next_item
        next_widget = self.containerclass(next_obj, **self.kwargs)
      File "/usr/share/alot/alot/widgets/search.py", line 27, in __init__
        self.rebuild()
      File "/usr/share/alot/alot/widgets/search.py", line 148, in rebuild
        minw, maxw, align_mode)
      File "/usr/share/alot/alot/widgets/search.py", line 106, in _build_part
        lastcontent = ' '.join([m.get_text_content() for m in msgs])
      File "/usr/share/alot/alot/db/message.py", line 250, in get_text_content
        return extract_body(self.get_email(), types=['text/plain'])
      File "/usr/share/alot/alot/db/message.py", line 73, in get_email
        self._email = message_from_file(f_mail)
      File "/usr/share/alot/alot/db/utils.py", line 110, in message_from_file
        ct = m.get_payload(1).get_content_type()
      File "/usr/lib/python2.7/email/message.py", line 193, in get_payload
        payload = self._payload[i]
    exceptions.IndexError: list index out of range

How could I debug the problem?

**Comment by lucc** [comment]
Maybe you can try to narrow down the search terms that produce this exception and find the actual mail (maybe binary search on the date for starters). That might help for actually debugging and fixing this.

**Comment by josch** [comment]
Found it. The following mail is responsible for the problem:

http://lists.debian.org/1472089225.9463.13.camel@jff-webhosting.net

Unfortunately, I wasn't able to debug the problem further. If I duplicate the email and just change the `Message-ID` header to a different value and then search just for this new message id, the bug does not happen. I thought that the problem might be tied to the thread, but I left the `In-Reply-To` header intact, so the message is still part of the same thread.

I do not know what I could try next.

**Comment by josch** [comment]
I found the message. I boiled it down to something more minimal which still exhibits the error I see:

    Subject: foo
    Message-ID: <testid0007>
    From: foo@bar.com
    To: blub@bla.org
    Date: Thu, 25 Aug 2016 12:03:20 +0200
    Content-Type: multipart/signed; micalg="pgp-sha256";
    	protocol="application/pgp-signature"; boundary="=-qos2UUhExL3w8bLP/h1v"
    Mime-Version: 1.0
    
    
    --=-qos2UUhExL3w8bLP/h1v
    Content-Type: text/plain; charset="UTF-8"
    Content-Transfer-Encoding: quoted-printable
    
    foobar
    --=-qos2UUhExL3w8bLP/h1v--
    

Does anything in there look funny?

**Comment by josch** [comment]
Okay, I think I got it. This is a signed message without a signature but while the db/utils.py checks for the message being of exactly two parts, it continues execution as if the message had two parts. Since it only has one, `m.get_payload(1)` fails with an `IndexError`. The following patch fixes the problem for me:

```diff
--- /usr/share/alot/alot/db/utils.py.bak	2016-08-25 12:10:36.406505401 +0200
+++ /usr/share/alot/alot/db/utils.py	2016-08-25 12:14:13.119038928 +0200
@@ -106,11 +106,11 @@
         if len(m.get_payload()) != 2:
             malformed = u'expected exactly two messages, got {0}'.format(
                 len(m.get_payload()))
-
-        ct = m.get_payload(1).get_content_type()
-        if ct != app_pgp_sig:
-            malformed = u'expected Content-Type: {0}, got: {1}'.format(
-                app_pgp_sig, ct)
+        else:
+            ct = m.get_payload(1).get_content_type()
+            if ct != app_pgp_sig:
+                malformed = u'expected Content-Type: {0}, got: {1}'.format(
+                    app_pgp_sig, ct)
 
         # TODO: RFC 3156 says the alg has to be lower case, but I've
         # seen a message with 'PGP-'. maybe we should be more
```

**Comment by pazz** [comment]
good catch, thanks. will you send a PR?

**Comment by josch** [comment]
Sorry, no time. :) Just copypaste the code. I require no attribution for it.

**Comment by pazz** [comment]
done, thanks.
