### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by josch** [pazz/alot#935]
Hi,

I'm running alot 0.3.6-1 and python-urwid 1.3.1-2+b1 from Debian. When I open an email with a huge binary attachment (5 MB in this case) and press `gf` to see the raw email and then scroll very far down, then I get:

    Traceback (most recent call last):
      File "/usr/bin/alot", line 20, in <module>
        main()
      File "/usr/share/alot/alot/init.py", line 186, in main
        UI(dbman, cmdstring)
      File "/usr/share/alot/alot/ui.py", line 87, in __init__
        self.mainloop.run()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
        self._run()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
        self.event_loop.run()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1200, in wrapper
        rval = f(*args,**kargs)
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
        callback()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 564, in entering_idle
        self.draw_screen()
      File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 578, in draw_screen
        canvas = self._topmost_widget.render(self.screen_size, focus=True)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
        canv = self._original_widget.render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1083, in render
        focus and self.focus_part == 'body')
      File "/usr/share/alot/alot/buffers.py", line 406, in render
        return self.body.render(size, focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 1751, in render
        canv = get_delegate(self).render(size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
        canv = fn(self, size, focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 457, in render
        (maxcol, maxrow), focus=focus)
      File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 380, in calculate_visible
        prev, pos = self.body.get_prev( pos )
      File "/usr/share/alot/alot/foreign/urwidtrees/widgets.py", line 83, in get_prev
        return self._get(self._tree.prev_position(pos))
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 118, in prev_position
        prevsib = self.prev_sibling_position(pos)  # is None if first
      File "/usr/share/alot/alot/foreign/urwidtrees/nested.py", line 357, in prev_sibling_position
        candidate = self._prev_sibling_position(self._tree, pos)
      File "/usr/share/alot/alot/foreign/urwidtrees/nested.py", line 353, in _prev_sibling_position
        candidate = (candidate) + (entry.last_sibling_position(entry.root),)
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 97, in last_sibling_position
        return self._last_in_direction(pos, self.next_sibling_position)
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 69, in _last_in_direction
        return self._last_in_direction(next_pos, direction)
      [...]
      # lots of repetition of above two lines
      [...]
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 65, in _last_in_direction
        next_pos = direction(starting_pos)
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 244, in next_sibling_position
        return self._confirm_pos(pos[:-1] + (pos[-1] + 1,))
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 216, in _confirm_pos
        if self._get_node(self._treelist, pos) is not None:
      File "/usr/share/alot/alot/foreign/urwidtrees/tree.py", line 208, in _get_node
        subtree = self._get_substructure(treelist, pos)
    RuntimeError: maximum recursion depth exceeded

I thought this issue was fixed with #711?

**Comment by zenhack** [comment]
The fix for #711 wasn't merged before 0.3.6 was released, so yes, it's fixed, but not in the version you're running. Should work in 0.3.7 or later (0.4.0 is current).
