### ISSUE TITLE
bufferlist command fails

### ISSUE THREAD

**Issue by pazz** [pazz/alot#946]
```
DEBUG:globals:CMDLINE: bufferlist 
DEBUG:ui:search command string: "bufferlist "
DEBUG:__init__:mode:search got commandline "bufferlist "
DEBUG:__init__:ARGS: [u'bufferlist']
DEBUG:__init__:cmd parms {}
ERROR:ui:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.4.dev0-py2.7.egg/alot/ui.py", line 662, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.4.dev0-py2.7.egg/alot/commands/globals.py", line 492, in apply
    bl = buffers.BufferlistBuffer(ui, self.filtfun)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.4.dev0-py2.7.egg/alot/buffers.py", line 70, in __init__
    self.rebuild()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot-0.4.dev0-py2.7.egg/alot/buffers.py", line 88, in rebuild
    displayedbuffers = [b for b in self.ui.buffers if self.filtfun(b)]
exceptions.TypeError: 'NoneType' object is not callable


```

**Comment by pazz** [comment]
the taglist command fails in the same way
