### ISSUE TITLE
Bufferlist doesn't work after 68f64472

### ISSUE THREAD

**Issue by dcbaker** [pazz/alot#958]
I've bisected this back to a commit I made (doh). I'm working on a fix now, but filing this bug in case anyone else runs into it. the stacktrace in the log looks like this:

```
INFO:ui:setup gui in 256 colours
ERROR:ui:Traceback (most recent call last):
  File "/home/dylan/.pyenv/versions/alot/lib/python2.7/site-packages/twisted/internet/defer.py", line 319, in addCallback
    callbackKeywords=kw)
  File "/home/dylan/.pyenv/versions/alot/lib/python2.7/site-packages/twisted/internet/defer.py", line 308, in addCallbacks
    self._runCallbacks()
  File "/home/dylan/.pyenv/versions/alot/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/dylan/source/alot/alot/ui.py", line 662, in call_apply
    return defer.maybeDeferred(cmd.apply, self)
--- <exception caught here> ---
  File "/home/dylan/.pyenv/versions/alot/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/dylan/source/alot/alot/commands/globals.py", line 488, in apply
    bl = buffers.BufferlistBuffer(ui, self.filtfun)
  File "/home/dylan/source/alot/alot/buffers.py", line 70, in __init__
    self.rebuild()
  File "/home/dylan/source/alot/alot/buffers.py", line 88, in rebuild
    displayedbuffers = [b for b in self.ui.buffers if self.filtfun(b)]
exceptions.TypeError: 'NoneType' object is not callable
```

It looks like therea re cases where filtun can be None (which would work with `map`, but not with a comprehension.

**Comment by dcbaker** [comment]
duplicate of #946
